"use client";

import { Fragment, useMemo, useState } from "react";
import { ArrowLeft, CircleHelp, Landmark, Wallet, HandCoins, ChartNoAxesCombined, ReceiptText, Scale } from "lucide-react";
import { MoneyValue } from "@/components/erp-ui";
import { ERPSelect } from "@/components/erp-select";
import { AccountingGoLive } from "@/components/accounting-go-live";
import { pdfColumns, pdfMoney, previewDataPdf, usePdfDataExport } from "@/components/pdf-data-export";

type Initial = Awaited<ReturnType<typeof import("@/lib/accounting").accountingSnapshot>>;
type Tab = "summary" | "movements" | "balances" | "cost";
const money = (cents: number) => (cents / 100).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const sourceLabel: Record<string, string> = { SUBCONTRACT_ACCRUAL: "اعتماد أعمال مقاول", SUBCONTRACT_PAYMENT: "دفعة مقاول", INCOMING_ACCRUAL: "استحقاق وارد", INCOMING_COLLECTION: "تحصيل وارد", OWNER_MATERIAL_RECEIPT: "استلام خامات", OWNER_MATERIAL_COST: "تحميل خامات", PURCHASE: "فاتورة مشتريات", PETTY_CASH: "حركة صندوق التشغيل", PAYROLL_APPROVAL: "اعتماد رواتب", PAYROLL_PAYMENT: "صرف رواتب", EMPLOYEE_ADVANCE: "سلفة موظف", BANK_MOVEMENT: "حركة بنكية" };
const typeLabel: Record<string, string> = { ASSET: "أصول", LIABILITY: "التزامات", EQUITY: "حقوق ملكية", REVENUE: "إيرادات", EXPENSE: "تكاليف ومصروفات" };
const tabs: [Tab, string][] = [["summary", "ملخص المحاسبة"], ["movements", "حركة الحسابات"], ["balances", "أرصدة الحسابات"], ["cost", "تكلفة المشروعات"]];
const netBalance = (type: string, debit: number, credit: number) => ["ASSET", "EXPENSE"].includes(type) ? debit - credit : credit - debit;
const balanceDirection = (type: string, net: number) => (["ASSET", "EXPENSE"].includes(type) ? net >= 0 : net < 0) ? "مدين" : "دائن";
const dateKey = (value: Date | string) => new Date(value).toISOString().slice(0, 10);

function Help({ text }: { text: string }) {
  return <details className="relative inline-block align-middle"><summary className="inline-flex size-6 cursor-pointer list-none items-center justify-center rounded-full border border-slate-200 text-slate-500 hover:bg-slate-50 focus-visible:outline-2 focus-visible:outline-blue-600" aria-label="شرح البند"><CircleHelp size={15} /></summary><span className="absolute end-0 top-8 z-30 w-64 rounded-xl border border-slate-200 bg-white p-3 text-start text-xs font-normal leading-6 text-slate-700 shadow-lg">{text}</span></details>;
}

function Metric({ label, value, detail, onClick, tone = "blue", icon: Icon, negativeLabel }: { label: string; value: number; detail: string; onClick: () => void; tone?: "blue" | "emerald" | "amber" | "violet" | "rose"; icon: typeof Wallet; negativeLabel?: string }) {
  const tones = { blue: "border-blue-200 bg-blue-50 text-blue-700", emerald: "border-emerald-200 bg-emerald-50 text-emerald-700", amber: "border-amber-200 bg-amber-50 text-amber-700", violet: "border-violet-200 bg-violet-50 text-violet-700", rose: "border-rose-200 bg-rose-50 text-rose-700" };
  return <article className="min-w-0 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm transition-shadow hover:shadow-md sm:p-5"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-2.5"><span className={`inline-flex size-9 shrink-0 items-center justify-center rounded-xl border ${tones[tone]}`}><Icon size={18} aria-hidden="true" /></span><h3 className="text-sm font-bold leading-6 text-slate-700">{label}</h3></div><Help text={detail} /></div><p className={`mt-4 truncate text-start text-xl font-black tabular-nums ${value < 0 ? "text-rose-700" : "text-slate-950"}`} dir="ltr" title={`${money(value)} ج.م`}>{money(value)} <span className="text-sm font-bold">ج.م</span></p>{value < 0 && negativeLabel && <p className="mt-1 text-xs font-bold text-rose-700">{negativeLabel}</p>}<button type="button" className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-blue-700 underline underline-offset-4 hover:text-blue-900" onClick={onClick}>عرض الحركات المكوِّنة <ArrowLeft size={13} /></button></article>;
}

export function AccountingCenter({ initial, canManage }: { initial: Initial; canManage: boolean }) {
  const [tab, setTab] = useState<Tab>("summary");
  const [accountId, setAccountId] = useState("");
  const [projectId, setProjectId] = useState("");
  const [query, setQuery] = useState("");
  const [fromDate, setFromDate] = useState("");
  const [toDate, setToDate] = useState("");
  const [openEntry, setOpenEntry] = useState<string | null>(null);
  const [movementPage, setMovementPage] = useState(1);
  const effectiveToDate = toDate || new Date().toLocaleDateString("en-CA", { timeZone: "Africa/Cairo" });
  const projectNames = useMemo(() => new Map(initial.projects.map((project) => [project.id, project.name])), [initial.projects]);
  const allLines = useMemo(() => initial.entries.flatMap((entry) => entry.lines.map((line) => ({ ...line, entry }))), [initial.entries]);
  const datedLines = useMemo(() => allLines.filter((line) => { const day = dateKey(line.entry.entryDate); return (!fromDate || day >= fromDate) && day <= effectiveToDate; }), [allLines, fromDate, effectiveToDate]);
  const visibleLines = useMemo(() => datedLines.filter((line) => { const term = query.trim().toLocaleLowerCase(); return (!accountId || line.accountId === accountId) && (!projectId || (line.projectId || line.entry.projectId) === projectId) && (!term || [line.account.name, line.account.code, line.entry.description, line.entry.number, sourceLabel[line.entry.sourceType || ""] || ""].some((value) => value.toLocaleLowerCase().includes(term))); }), [datedLines, accountId, projectId, query]);
  const pageCount = Math.max(1, Math.ceil(visibleLines.length / 25));
  const currentPage = Math.min(movementPage, pageCount);
  const pageLines = visibleLines.slice((currentPage - 1) * 25, currentPage * 25);
  const throughDateLines = useMemo(() => allLines.filter((line) => dateKey(line.entry.entryDate) <= effectiveToDate), [allLines, effectiveToDate]);
  const balanceRows = useMemo(() => initial.accounts.map((account) => {
    const matched = throughDateLines.filter((line) => line.accountId === account.id && (!projectId || (line.projectId || line.entry.projectId) === projectId));
    const debit = matched.reduce((sum, line) => sum + line.debitCents, 0);
    const credit = matched.reduce((sum, line) => sum + line.creditCents, 0);
    return { account, debit, credit, net: netBalance(account.type, debit, credit) };
  }).filter((row) => row.debit || row.credit), [initial.accounts, throughDateLines, projectId]);
  const totals = useMemo(() => {
    const value = (key: string) => balanceRows.find((row) => row.account.systemKey === key)?.net || 0;
    const periodValue = (key: string) => datedLines.filter((line) => line.account.systemKey === key && (!projectId || (line.projectId || line.entry.projectId) === projectId)).reduce((sum, line) => sum + line.creditCents - line.debitCents, 0);
    const periodCost = datedLines.filter((line) => line.account.type === "EXPENSE" && (!projectId || (line.projectId || line.entry.projectId) === projectId)).reduce((sum, line) => sum + line.debitCents - line.creditCents, 0);
    return { cash: value("BANK") + value("PETTY_CASH"), receivable: value("OWNER_RECEIVABLE"), payable: value("SUBCONTRACTOR_PAYABLE") + value("PAYROLL_PAYABLE") + value("RETENTION_PAYABLE") + value("SUBCONTRACTOR_DEDUCTIONS"), revenue: periodValue("CONTRACT_REVENUE"), cost: periodCost };
  }, [balanceRows, datedLines, projectId]);
  const centers = useMemo(() => initial.projects.map((project) => { const expenses = datedLines.filter((line) => (line.projectId || line.entry.projectId) === project.id && line.account.type === "EXPENSE"); const byAccount = new Map<string, { name: string; cents: number }>(); for (const line of expenses) { const row = byAccount.get(line.accountId) || { name: line.account.name, cents: 0 }; row.cents += line.debitCents - line.creditCents; byAccount.set(line.accountId, row); } return { project, cents: expenses.reduce((sum, line) => sum + line.debitCents - line.creditCents, 0), breakdown: [...byAccount.entries()].map(([id, row]) => ({ id, ...row })).filter((row) => row.cents) }; }).filter((row) => row.cents), [initial.projects, datedLines]);
  const debit = balanceRows.reduce((sum, row) => sum + row.debit, 0);
  const credit = balanceRows.reduce((sum, row) => sum + row.credit, 0);
  const periodText = fromDate || toDate ? `${fromDate || "البداية"} — ${effectiveToDate}` : `حتى ${effectiveToDate}`;
  const showMovements = (id: string, project = "", throughDate = false) => { setAccountId(id); setProjectId(project); if (throughDate) setFromDate(""); setTab("movements"); setMovementPage(1); setOpenEntry(null); };

  usePdfDataExport(() => {
    const report = tab === "movements" ? { title: "حركة الحسابات", tables: [{ columns: pdfColumns(["التاريخ", 2], ["الحساب", 2], ["البيان", 3], ["المصدر", 2], ["المشروع", 2], ["مدين", 2], ["دائن", 2]), rows: visibleLines.map((line) => [dateKey(line.entry.entryDate), `${line.account.name} · ${line.account.code}`, line.entry.description, sourceLabel[line.entry.sourceType || ""] || "قيد يدوي/تسوية", projectNames.get(line.projectId || line.entry.projectId || "") || "عام الشركة", line.debitCents ? pdfMoney(line.debitCents) : "—", line.creditCents ? pdfMoney(line.creditCents) : "—"]) }] }
      : tab === "cost" ? { title: "تكلفة المشروعات من القيود", tables: [{ columns: pdfColumns(["المشروع", 3], ["الحساب", 3], ["التكلفة المسجلة", 2]), rows: centers.flatMap((row) => row.breakdown.map((part) => [row.project.name, part.name, pdfMoney(part.cents)])) }] }
      : { title: tab === "balances" ? "أرصدة الحسابات" : "ملخص المحاسبة والقيود", tables: [{ columns: pdfColumns(["الكود", 2], ["الحساب", 3], ["النوع", 2], ["الرصيد الصافي", 2], ["مدين", 2], ["دائن", 2]), rows: balanceRows.map(({ account, net, debit, credit }) => [account.code, account.name, typeLabel[account.type] || account.type, `${pdfMoney(Math.abs(net))} ${balanceDirection(account.type, net)}`, pdfMoney(debit), pdfMoney(credit)]) }] };
    void previewDataPdf({ ...report, filters: `الحركة خلال ${periodText} · الأرصدة حتى ${effectiveToDate}${projectId ? ` · ${projectNames.get(projectId) || "المشروع"}` : ""}`, kpis: tab === "summary" ? [{ label: projectId ? "صافي حركة النقدية المرتبطة بالمشروع" : "النقدية المسجلة حتى التاريخ", value: pdfMoney(totals.cash), tone: "blue" }, { label: totals.receivable < 0 ? "رصيد دائن للجهات المالكة" : "مستحق لنا من الجهات المالكة", value: pdfMoney(Math.abs(totals.receivable)), tone: "emerald" }, { label: "التزامات حتى التاريخ", value: pdfMoney(totals.payable), tone: "amber" }, { label: "تكلفة خلال الفترة", value: pdfMoney(totals.cost), tone: "violet" }] : [] });
  });

  return <div className="space-y-5">
    <section><p className="text-xs font-bold text-blue-700">المركز المحاسبي</p><h1 className="mt-1 text-2xl font-black text-slate-950">المحاسبة والقيود</h1><p className="mt-2 text-sm text-slate-500">من أين جاءت الأرقام؟ افتح أي رصيد للاطلاع على الحركات التي كوّنته.</p></section>
    <AccountingGoLive value={initial.goLiveDate} canManage={canManage} />
    <nav className="flex flex-wrap gap-2 rounded-xl border bg-white p-2" aria-label="أقسام المحاسبة">{tabs.map(([key, label]) => <button key={key} type="button" onClick={() => setTab(key)} aria-current={tab === key ? "page" : undefined} className={`rounded-lg px-4 py-2 text-sm font-bold ${tab === key ? "bg-blue-700 text-white" : "text-slate-600 hover:bg-slate-100"}`}>{label}</button>)}</nav>
    <section className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm sm:p-4" aria-label="فلاتر المحاسبة"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-100 pb-3"><h2 className="text-sm font-black text-slate-800">تحديد نطاق العرض</h2><button type="button" className="rounded-lg px-2 py-1 text-xs font-bold text-blue-700 hover:bg-blue-50" onClick={() => { setFromDate(""); setToDate(""); setProjectId(""); setAccountId(""); setQuery(""); setMovementPage(1); }}>مسح الفلاتر</button></div><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label className="grid gap-1 text-xs font-bold text-slate-600">من تاريخ<input type="date" value={fromDate} onChange={(event) => { const next = event.target.value; setFromDate(next); if (toDate && next > toDate) setToDate(""); setMovementPage(1); }} className="erp-control" /></label><label className="grid gap-1 text-xs font-bold text-slate-600">إلى تاريخ<input type="date" value={toDate} min={fromDate || undefined} onChange={(event) => { setToDate(event.target.value); setMovementPage(1); }} className="erp-control" /></label><label className="grid gap-1 text-xs font-bold text-slate-600">المشروع<ERPSelect value={projectId} onValueChange={(value) => { setProjectId(value); setMovementPage(1); }}><option value="">كل المشروعات وعام الشركة</option>{initial.projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</ERPSelect></label></div></section>
    <p className="text-xs text-slate-500">الحركة خلال: {periodText} · الأرصدة حتى: {effectiveToDate}{projectId ? ` · ${projectNames.get(projectId) || "المشروع"}` : " · جميع المشروعات وعام الشركة"}</p>
    {tab === "summary" && <div className="space-y-6">
      <section aria-labelledby="accounting-balances-title"><div className="mb-3 flex flex-wrap items-baseline justify-between gap-2"><div><h2 id="accounting-balances-title" className="text-base font-black text-slate-900">الموقف حتى التاريخ المحدد</h2><p className="mt-1 text-xs text-slate-500">أرصدة تراكمية حسب القيود المسجلة حتى {effectiveToDate}.</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">أرصدة</span></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><Metric icon={Wallet} tone="blue" label={projectId ? "صافي حركة النقدية المرتبطة بالمشروع" : "النقدية المسجلة"} value={totals.cash} detail={projectId ? "صافي القيود النقدية المرتبطة بالمشروع، وليس رصيد خزنة مستقلة له." : "رصيد البنك وصندوق التشغيل من القيود حتى التاريخ المحدد."} onClick={() => setTab("balances")} /><Metric icon={HandCoins} tone="emerald" label={totals.receivable < 0 ? "رصيد دائن للجهات المالكة" : "مستحق لنا من الجهات المالكة"} value={Math.abs(totals.receivable)} detail={totals.receivable < 0 ? "الرصيد دائن حاليًا في حساب الجهات المالكة؛ لا يُعرض كمبلغ مستحق لنا. افتح الحركات لمراجعته." : "استحقاقات الجهات المالكة بعد التحصيل وتسوية شهادات الخامات."} onClick={() => showMovements(initial.accounts.find((item) => item.systemKey === "OWNER_RECEIVABLE")?.id || "", "", true)} /><Metric icon={Landmark} tone="amber" label="التزامات مسجلة" value={totals.payable} detail="مستحقات مقاولي الباطن والرواتب والاستقطاعات والتأمينات المحتجزة." onClick={() => setTab("balances")} /></div></section>
      <section aria-labelledby="accounting-period-title"><div className="mb-3 flex flex-wrap items-baseline justify-between gap-2"><div><h2 id="accounting-period-title" className="text-base font-black text-slate-900">نشاط الفترة</h2><p className="mt-1 text-xs text-slate-500">إيراد وتكلفة محاسبيان خلال {periodText}، ولا يعنيان بالضرورة تحصيلًا أو صرفًا نقديًا.</p></div><span className="rounded-full bg-violet-50 px-3 py-1 text-xs font-bold text-violet-700">حركة</span></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><Metric icon={ChartNoAxesCombined} tone="emerald" label="إيراد أعمال مسجل" value={totals.revenue} detail="إيراد مستخلصات مسجل محاسبيًا، سواء تم تحصيله أم لا." onClick={() => showMovements(initial.accounts.find((item) => item.systemKey === "CONTRACT_REVENUE")?.id || "")} /><Metric icon={ReceiptText} tone="amber" label="تكلفة ومصروفات مسجلة" value={totals.cost} detail="تكاليف ومصروفات مرحلة؛ ليست بالضرورة نقدًا خرج." onClick={() => setTab("cost")} /><Metric icon={Scale} tone={totals.revenue - totals.cost < 0 ? "rose" : "violet"} label="فرق الإيراد والتكلفة" value={totals.revenue - totals.cost} detail="فرق إرشادي بين الإيراد والتكلفة المسجلين، وليس قائمة أرباح وخسائر معتمدة." onClick={() => setTab("balances")} /></div></section>
      <section className="flex flex-wrap items-center gap-x-5 gap-y-2 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3"><h2 className="text-sm font-black text-slate-800">حالة الدفتر</h2><span className="text-xs text-slate-600">{initial.accounts.length} حساب</span><span className="text-xs text-slate-600">{initial.entries.length} قيد</span><span className="text-xs text-slate-600">المدين {money(debit)} ج.م · الدائن {money(credit)} ج.م</span><Help text="تساوي إجمالي المدين والدائن طبيعي في القيد المتوازن؛ لا يمثلان الأموال الداخلة والخارجة." /></section>
    </div>}
    {tab === "movements" && <section className="erp-table-shell">
      <div className="grid gap-3 border-b bg-white p-4 md:grid-cols-2"><label className="grid gap-1 text-xs font-bold">الحساب<ERPSelect value={accountId} onValueChange={(value) => { setAccountId(value); setMovementPage(1); }}><option value="">كل الحسابات</option>{initial.accounts.map((account) => <option key={account.id} value={account.id}>{account.code} — {account.name}</option>)}</ERPSelect></label><label className="grid gap-1 text-xs font-bold">بحث في رقم القيد أو البيان<input className="erp-control" value={query} onChange={(event) => { setQuery(event.target.value); setMovementPage(1); }} placeholder="ابحث في الحركات..." /></label></div>
      <div className="flex items-center justify-between gap-3 border-b bg-slate-50 px-4 py-2 text-xs text-slate-600"><span>{visibleLines.length} حركة مطابقة</span><span>اضغط «عرض القيد» لرؤية طرفيه كاملين</span></div>
      <div className="erp-table-scroll"><table className="erp-data-table min-w-[950px]"><thead><tr>{["التاريخ", "الحساب", "البيان", "المصدر", "المشروع", "مدين", "دائن", "القيد"].map((head) => <th key={head}>{head}</th>)}</tr></thead><tbody>{pageLines.map((line) => <Fragment key={line.id}><tr><td dir="ltr">{dateKey(line.entry.entryDate)}</td><td><b>{line.account.name}</b><p className="text-xs text-slate-400">{line.account.code}</p></td><td>{line.entry.description}<p className="mt-1 text-[11px] font-semibold text-slate-500">بواسطة: {line.entry.actor}</p></td><td>{sourceLabel[line.entry.sourceType || ""] || "قيد يدوي/تسوية"}</td><td>{projectNames.get(line.projectId || line.entry.projectId || "") || "عام الشركة"}</td><td>{line.debitCents ? <MoneyValue>{money(line.debitCents)} ج.م</MoneyValue> : "—"}</td><td>{line.creditCents ? <MoneyValue>{money(line.creditCents)} ج.م</MoneyValue> : "—"}</td><td><button type="button" className="text-xs font-bold text-blue-700 underline" aria-expanded={openEntry === line.id} onClick={() => setOpenEntry(openEntry === line.id ? null : line.id)}>{openEntry === line.id ? "إغلاق" : `عرض ${line.entry.number}`}</button></td></tr>{openEntry === line.id && <tr className="bg-blue-50/60"><td colSpan={8} className="p-4"><div className="mx-auto max-w-3xl rounded-xl border border-blue-200 bg-white p-4 text-xs"><p className="mb-2 font-black text-slate-900">القيد {line.entry.number} · {line.entry.description}</p><p className="mb-2 text-slate-600">بواسطة: {line.entry.actor}</p><div className="grid grid-cols-[1fr_auto_auto] gap-x-4 border-b py-2 font-bold text-slate-500"><span>الحساب</span><span>مدين</span><span>دائن</span></div>{line.entry.lines.map((part) => <div key={part.id} className="grid grid-cols-[1fr_auto_auto] gap-x-4 border-b py-2 last:border-0"><span>{part.account.name}</span><span dir="ltr">{part.debitCents ? money(part.debitCents) : "—"}</span><span dir="ltr">{part.creditCents ? money(part.creditCents) : "—"}</span></div>)}</div></td></tr>}</Fragment>)}{!visibleLines.length && <tr><td colSpan={8} className="p-10 text-center text-slate-400">لا توجد حركات ضمن الاختيارات الحالية. غيّر الفلاتر أو امسحها لعرض المزيد.</td></tr>}</tbody></table></div>
      {pageCount > 1 && <div className="flex items-center justify-between gap-3 border-t bg-white p-3 text-xs"><span>صفحة {currentPage} من {pageCount}</span><div className="flex gap-2"><button type="button" disabled={currentPage <= 1} className="rounded-lg border px-3 py-1.5 font-bold text-blue-700 disabled:opacity-40" onClick={() => setMovementPage(currentPage - 1)}>السابق</button><button type="button" disabled={currentPage >= pageCount} className="rounded-lg border px-3 py-1.5 font-bold text-blue-700 disabled:opacity-40" onClick={() => setMovementPage(currentPage + 1)}>التالي</button></div></div>}
    </section>}
    {tab === "balances" && <section className="erp-table-shell"><div className="border-b bg-white p-4"><h2 className="font-black">أرصدة الحسابات</h2><p className="mt-1 text-xs text-slate-500">الرصيد الصافي حتى {effectiveToDate}، مع إبقاء إجمالي المدين والدائن للمراجعة. اضغط على أي حساب لرؤية مصدر رصيده.</p></div><div className="erp-table-scroll"><table className="erp-data-table min-w-[850px]"><thead><tr><th>الكود</th><th>الحساب</th><th>المجموعة</th><th>الرصيد الصافي</th><th>مدين</th><th>دائن</th><th>التفاصيل</th></tr></thead><tbody>{balanceRows.map(({ account, debit, credit, net }) => <tr key={account.id}><td>{account.code}</td><td className="font-bold">{account.name}</td><td><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold text-slate-600">{typeLabel[account.type] || account.type}</span></td><td><MoneyValue>{money(Math.abs(net))} ج.م</MoneyValue> <span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${balanceDirection(account.type, net) === "دائن" ? "bg-violet-50 text-violet-700" : "bg-blue-50 text-blue-700"}`}>{balanceDirection(account.type, net)}</span></td><td>{money(debit)} ج.م</td><td>{money(credit)} ج.م</td><td><button type="button" className="inline-flex items-center gap-1 text-xs font-bold text-blue-700 underline" onClick={() => showMovements(account.id, "", true)}>عرض الحركات <ArrowLeft size={13} /></button></td></tr>)}{!balanceRows.length && <tr><td colSpan={7} className="py-12 text-center text-slate-400">لا توجد قيود حتى التاريخ المحدد.</td></tr>}</tbody></table></div></section>}
    {tab === "cost" && <section className="erp-table-shell"><div className="border-b bg-white p-4"><h2 className="font-black">تكلفة المشروعات من القيود</h2><p className="mt-1 text-xs text-slate-500">التكلفة المسجلة على المشروع، لا النقد المنصرف بالضرورة. اضغط على حساب التكلفة لرؤية الحركات.</p></div><div className="space-y-3 p-4">{centers.map(({ project, cents, breakdown }) => <div key={project.id} className="rounded-xl border bg-white p-4"><div className="flex justify-between gap-3 font-bold"><span>{project.name}</span><MoneyValue>{money(cents)} ج.م</MoneyValue></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{breakdown.map((part) => <button key={part.id} type="button" className="flex justify-between gap-2 rounded-lg border px-3 py-2 text-start text-xs hover:border-blue-300 hover:bg-blue-50" onClick={() => showMovements(part.id, project.id)}><span>{part.name}</span><span className="font-bold text-blue-700">{money(part.cents)} ج.م</span></button>)}</div></div>)}{!centers.length && <p className="p-10 text-center text-slate-400">لا توجد تكاليف مرحلة على المشروعات ضمن الفترة المحددة.</p>}</div></section>}
  </div>;
}
