import { BookOpenCheck, CalendarDays, Scale } from "lucide-react";
import { KpiCard, MoneyValue } from "@/components/erp-ui";
import { AccountingGoLive } from "@/components/accounting-go-live";

const money = (cents: number) => (cents / 100).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export function AccountingCenter({ initial, canManage }: { initial: Awaited<ReturnType<typeof import("@/lib/accounting").accountingSnapshot>>; canManage: boolean }) {
  const debit = initial.trialBalance.reduce((sum, row) => sum + row.debit, 0), credit = initial.trialBalance.reduce((sum, row) => sum + row.credit, 0);
  return <div className="space-y-5"><section><p className="text-xs font-bold text-blue-700">Phase 10 · Accounting</p><h1 className="mt-1 text-2xl font-black text-slate-950">المحاسبة والقيود</h1><p className="mt-2 text-sm text-slate-500">دليل الحسابات والأستاذ وميزان المراجعة. القيود الآلية تبدأ عند تحديد تاريخ التشغيل النهائي.</p></section><AccountingGoLive value={initial.goLiveDate} canManage={canManage} /><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="حسابات الدليل" value={String(initial.accounts.length)} icon={BookOpenCheck} tone="blue" /><KpiCard label="قيود مرحّلة" value={String(initial.entries.length)} icon={CalendarDays} tone="violet" /><KpiCard label="إجمالي المدين" value={`${money(debit)} ج.م`} icon={Scale} tone="emerald" /><KpiCard label="إجمالي الدائن" value={`${money(credit)} ج.م`} icon={Scale} tone="amber" /></section><section className="erp-table-shell"><div className="border-b bg-white p-4"><h2 className="font-black">دليل الحسابات</h2><p className="mt-1 text-xs text-slate-500">الحسابات الأساسية محمية؛ يضيف المحاسب أو المدير التنفيذي الحسابات الفرعية لاحقًا.</p></div><div className="erp-table-scroll"><table className="erp-data-table min-w-[720px]"><thead><tr><th>الكود</th><th>الحساب</th><th>النوع</th><th>مدين</th><th>دائن</th></tr></thead><tbody>{initial.trialBalance.map(({ account, debit, credit }) => <tr key={account.id}><td>{account.code}</td><td className="font-bold">{account.name}</td><td>{account.type}</td><td><MoneyValue>{money(debit)} ج.م</MoneyValue></td><td><MoneyValue>{money(credit)} ج.م</MoneyValue></td></tr>)}{!initial.trialBalance.length && <tr><td colSpan={5} className="py-12 text-center text-slate-400">لا توجد قيود بعد؛ سيتم البدء بالأرصدة الافتتاحية عند تحديد تاريخ التشغيل.</td></tr>}</tbody></table></div></section></div>;
}
