"use client";
/* eslint-disable jsx-a11y/alt-text -- @react-pdf/renderer Image does not expose an alt prop. */

import { Document, Font, Image, Page, StyleSheet, Text, View, pdf } from "@react-pdf/renderer";
import { companyBrand } from "@/lib/company-brand";

export type PdfColumn = { label: string; width: number };
export type PdfTable = { columns: PdfColumn[]; rows: string[][]; footer?: string[] };
export type PdfKpi = { label: string; value: string; tone?: "blue" | "emerald" | "amber" | "violet" | "rose" };

const palette = { navy: "#10192d", blue: "#168dcc", ink: "#172033", muted: "#667085", border: "#cbd5e1", alternate: "#f6f9fc", total: "#eaf4ff" };
const styles = StyleSheet.create({
  page: { fontFamily: "ASGCCairo", color: palette.ink, fontSize: 8.5, paddingTop: 166, paddingBottom: 54, paddingHorizontal: 26 }, header: { position: "absolute", top: 18, left: 26, right: 26 },
  headerBox: { flexDirection: "row-reverse", alignItems: "center", backgroundColor: palette.navy, borderRadius: 5, paddingVertical: 8, paddingHorizontal: 12, borderBottomWidth: 3, borderBottomColor: palette.blue }, logo: { width: 42, height: 42, objectFit: "contain", backgroundColor: "#ffffff", borderRadius: 4 }, headerTitles: { flex: 1, marginHorizontal: 10, textAlign: "right" }, company: { color: "#ffffff", fontSize: 12, fontWeight: 700 }, system: { color: "#bcd4e7", fontSize: 8, marginTop: 2 }, headerMeta: { width: 150, color: "#dbeafe", fontSize: 7.5, textAlign: "left" },
  titleRow: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "flex-end", marginTop: 8 }, title: { fontSize: 14, fontWeight: 700, color: palette.navy }, subtitle: { color: palette.muted, fontSize: 8 }, filter: { marginTop: 4, paddingTop: 4, borderTopWidth: 0.6, borderTopColor: palette.border, color: palette.muted, fontSize: 7.5, textAlign: "right" }, kpiRow: { flexDirection: "row-reverse", gap: 5, marginTop: 7 }, kpi: { flexGrow: 1, flexBasis: 0, borderWidth: 0.8, borderRadius: 4, paddingVertical: 5, paddingHorizontal: 6, textAlign: "center" }, kpiLabel: { color: palette.muted, fontSize: 7.2, textAlign: "center" }, kpiValue: { marginTop: 2, color: palette.navy, fontSize: 9, fontWeight: 700, textAlign: "center" }, kpiBlue: { borderColor: "#9fc8f3", backgroundColor: "#eef6ff" }, kpiEmerald: { borderColor: "#9ee8cc", backgroundColor: "#eefff7" }, kpiAmber: { borderColor: "#f3d190", backgroundColor: "#fff9e8" }, kpiViolet: { borderColor: "#c7b6f3", backgroundColor: "#f6f2ff" }, kpiRose: { borderColor: "#f0b9c5", backgroundColor: "#fff3f5" },
  table: { width: "100%", borderTopWidth: 1, borderLeftWidth: 1, borderColor: palette.border }, headerRow: { flexDirection: "row-reverse", backgroundColor: palette.blue }, row: { flexDirection: "row-reverse" }, alternate: { backgroundColor: palette.alternate }, total: { backgroundColor: palette.total },
  headerCell: { color: "#ffffff", borderRightWidth: 1, borderBottomWidth: 1, borderColor: "#0b6fa6", paddingHorizontal: 4, paddingVertical: 5, fontSize: 8, fontWeight: 700, textAlign: "center" }, cell: { borderRightWidth: 1, borderBottomWidth: 1, borderColor: palette.border, paddingHorizontal: 4, paddingVertical: 4, lineHeight: 1.3, textAlign: "right" }, totalCell: { fontWeight: 700, color: palette.navy }, empty: { padding: 16, color: palette.muted, textAlign: "center" },
  footer: { position: "absolute", bottom: 10, left: 26, right: 26, borderTopWidth: 0.6, borderTopColor: palette.border, paddingTop: 4, flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "flex-end", color: palette.muted }, footerContact: { width: 360, textAlign: "right", fontSize: 5.8, lineHeight: 1.45 }, footerPage: { flex: 1, textAlign: "left", fontSize: 6.5, paddingBottom: 1 },
});
function safe(value: unknown) { const text = String(value ?? "—").replace(/[\u0000-\u0008\u000B-\u001F\u007F-\u009F\u200B-\u200F\u202A-\u202E\u2066-\u2069\uFEFF]/g, "").replace(/\s+/g, " ").trim(); return text || "—"; }
function ReportTable({ table }: { table: PdfTable }) { const totalWeight = table.columns.reduce((sum, column) => sum + column.width, 0) || 1; const width = (index: number) => `${(table.columns[index].width / totalWeight) * 100}%`; if (!table.rows.length) return <Text style={styles.empty}>لا توجد بيانات مطابقة للفلاتر الحالية</Text>; return <View style={styles.table}><View fixed style={styles.headerRow}>{table.columns.map((column, index) => <Text key={column.label + index} style={[styles.headerCell, { width: width(index) }]}>{safe(column.label)}</Text>)}</View>{table.rows.map((row, rowIndex) => <View key={rowIndex} wrap={false} style={[styles.row, rowIndex % 2 ? styles.alternate : {}]}>{table.columns.map((column, columnIndex) => <Text key={column.label + columnIndex} style={[styles.cell, { width: width(columnIndex) }]}>{safe(row[columnIndex])}</Text>)}</View>)}{table.footer ? <View wrap={false} style={[styles.row, styles.total]}>{table.columns.map((column, index) => <Text key={column.label + index} style={[styles.cell, styles.totalCell, { width: width(index) }]}>{safe(table.footer?.[index])}</Text>)}</View> : null}</View>; }
export function PdfReportDocument({ title, filters, tables, kpis = [], userName }: { title: string; filters?: string; tables: PdfTable[]; kpis?: PdfKpi[]; userName?: string }) { const now = new Date(); const exportDate = new Intl.DateTimeFormat("ar-EG", { dateStyle: "long" }).format(now); const exportTime = new Intl.DateTimeFormat("ar-EG", { timeStyle: "short" }).format(now); const origin = typeof window === "undefined" ? "" : window.location.origin; return <Document title={safe(title)}><Page size="A4" orientation="landscape" style={styles.page} wrap><View fixed style={styles.header}><View style={styles.headerBox}><Image src={`${origin}${companyBrand.logoPath}`} style={styles.logo} /><View style={styles.headerTitles}><Text style={styles.company}>{companyBrand.arabicName}</Text><Text style={styles.system}>{companyBrand.englishName} · منظومة إدارة المقاولات والمشروعات</Text></View><View style={styles.headerMeta}><Text>الوقت: {exportTime}</Text><Text>تاريخ التصدير: {exportDate}</Text><Text>المستخدم: {safe(userName)}</Text></View></View><View style={styles.titleRow}><Text style={styles.title}>{safe(title)}</Text><Text style={styles.subtitle}>تقرير صادر من {companyBrand.systemName}</Text></View>{filters ? <Text style={styles.filter}>الفلاتر المطبقة: {safe(filters)}</Text> : null}{kpis.length ? <View style={styles.kpiRow}>{kpis.slice(0, 5).map((kpi, index) => <View key={`${kpi.label}-${index}`} style={[styles.kpi, styles[`kpi${(kpi.tone || "blue")[0].toUpperCase()}${(kpi.tone || "blue").slice(1)}` as "kpiBlue"]]}><Text style={styles.kpiLabel}>{safe(kpi.label)}</Text><Text style={styles.kpiValue}>{safe(kpi.value)}</Text></View>)}</View> : null}</View>{tables.map((table, index) => <View key={index} style={{ marginTop: index ? 16 : 8 }}><ReportTable table={table} /></View>)}<View fixed style={styles.footer}><View style={styles.footerContact}><Text>العنوان: {companyBrand.address}</Text><Text>الهاتف: {companyBrand.phone}</Text><Text>الموقع الإلكتروني: {companyBrand.website}</Text></View><Text style={styles.footerPage} render={({ pageNumber, totalPages }) => `صفحة ${pageNumber} من ${totalPages}`} /></View></Page></Document>; }
let registered = false;
export async function createPdfReportUrl(props: React.ComponentProps<typeof PdfReportDocument>) { if (!registered) { const origin = window.location.origin; Font.register({ family: "ASGCCairo", fonts: [{ src: `${origin}/fonts/Cairo-Regular.ttf`, fontWeight: "normal" }, { src: `${origin}/fonts/Cairo-Bold.ttf`, fontWeight: "bold" }] }); registered = true; } const blob = await pdf(<PdfReportDocument {...props} />).toBlob(); return URL.createObjectURL(blob); }
