"use client";
import { useState, type FormEvent } from "react";
import type { ProjectCostControl } from "@/lib/project-cost-control";
import { costCategories, type CostCategory } from "@/lib/project-planning-math";

const cash = (cents: number | null) => cents === null ? "—" : `${(cents / 100).toLocaleString("en-US", { minimumFractionDigits: 2 })} ج.م`;
const toCents = (value: FormDataEntryValue | null) => Math.round(Number(String(value || 0).replaceAll(",", "")) * 100);
function MoneyInput({ name, defaultValue, placeholder }: { name: string; defaultValue?: number | string; placeholder?: string }) { const initial = Number(defaultValue || 0); const [value, setValue] = useState(Number.isFinite(initial) && initial !== 0 ? initial.toLocaleString("en-US", { maximumFractionDigits: 2 }) : ""); return <div className="relative mt-1"><input name={name} type="text" inputMode="decimal" value={value} placeholder={placeholder} onChange={(event) => { const raw = event.target.value.replace(/[^0-9.]/g, ""); if (raw === "") { setValue(""); return; } const number = Number(raw.replaceAll(",", "")); setValue(Number.isFinite(number) ? number.toLocaleString("en-US", { maximumFractionDigits: 2 }) : value); }} className="erp-control no-number-spinner pe-14 text-right" dir="ltr" /><span className="pointer-events-none absolute inset-y-0 end-3 flex items-center text-xs font-bold text-slate-400">ج.م</span></div>; }
function PercentInput({ name, defaultValue }: { name: string; defaultValue?: number | string }) { return <div className="relative mt-1"><input name={name} type="number" inputMode="decimal" min="0" max="100" step="0.1" defaultValue={defaultValue} onInput={(event) => { const input = event.currentTarget; if (Number(input.value) > 100) input.value = "100"; if (Number(input.value) < 0) input.value = "0"; }} className="erp-control no-number-spinner pe-10 text-right" dir="rtl" /><span className="pointer-events-none absolute inset-y-0 end-3 flex items-center text-sm font-bold text-slate-400">%</span></div>; }

export function ProjectPlanningPanel({ data, canManage, onChange }: { data: ProjectCostControl; canManage: boolean; onChange: (value: ProjectCostControl) => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [editingId, setEditingId] = useState<string | null>(null); const [editingValue, setEditingValue] = useState("");
  async function send(body: object) { setBusy(true); setError(""); try { const response = await fetch("/api/project-cost-control/planning", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); const refreshed = await fetch(`/api/project-cost-control?projectId=${encodeURIComponent(data.project.id)}`); onChange(await refreshed.json()); } catch (reason) { setError(reason instanceof Error ? reason.message : "تعذر الحفظ"); } finally { setBusy(false); } }
  async function savePlan(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const budget = Object.fromEntries(Object.keys(costCategories).map(key => [key, toCents(form.get(key))])); const progress = form.get("progress"); await send({ action: "plan", projectId: data.project.id, revision: data.planning.revision, budget, progressPercent: progress === "" ? null : Number(progress), progressDate: progress === "" ? null : String(form.get("progressDate")) }); }
  async function saveCommitment(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const source = data.planning.sources.find(item => item.sourceId === form.get("sourceId")); if (!source) return; await send({ action: "commitment", projectId: data.project.id, revision: 0, name: String(form.get("name")), category: source.category, partyType: source.partyType, partyId: source.partyId, totalCents: toCents(form.get("amount")), active: true, sources: [{ sourceType: source.sourceType, sourceId: source.sourceId }] }); formElement.reset(); }
  async function updateCommitment(item: ProjectCostControl["planning"]["commitments"][number], active: boolean, amount = item.totalCents) { await send({ action: "commitment", projectId: data.project.id, id: item.id, revision: item.revision, name: item.name, category: item.category, partyType: item.partyType, partyId: item.partyId, totalCents: amount, active, sources: item.sources.map(link => ({ sourceType: link.sourceType, sourceId: link.sourceId })) }); }
  const f = data.planning.forecast;
  return <section className="space-y-4 rounded-2xl border bg-white p-5 shadow-sm" dir="rtl"><div><h2 className="text-lg font-black">موقف المشروع — أين نحن وإلى أين نتجه؟</h2><p className="mt-1 text-sm leading-6 text-slate-600">هذه الخلاصة تساعدك تعرف: كم كانت الميزانية، كم صُرف فعليًا، ما الذي التزمنا به ولم يُنفذ بعد، وكم نتوقع أن تنتهي تكلفة المشروع.</p><p className="mt-1 text-xs text-slate-500">التكلفة المتوقعة مبنية على استمرار معدل الصرف الحالي حتى نسبة الإنجاز المسجلة.</p></div>{error && <p className="rounded-lg bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}
    {canManage && <form onSubmit={savePlan} className="grid gap-3 rounded-xl border-2 border-blue-100 bg-blue-50/40 p-4 md:grid-cols-3"><div className="md:col-span-3"><h3 className="font-black">أدخل ميزانية المشروع ونسبة الإنجاز</h3><p className="mt-1 text-xs text-slate-500">هذه البيانات هي أساس مؤشرات التوقع التالية.</p></div>{(Object.keys(costCategories) as CostCategory[]).map(key=><label key={key} className="text-xs font-bold">ميزانية {costCategories[key]}<MoneyInput name={key} defaultValue={(data.planning.budget?.[key] ?? 0)/100} /></label>)}<label className="text-xs font-bold">نسبة الإنجاز<PercentInput name="progress" defaultValue={data.planning.progressPercent ?? ""} /></label><label className="text-xs font-bold">تاريخ القياس<input name="progressDate" type="date" defaultValue={data.planning.progressDate ?? new Date().toISOString().slice(0,10)} className="erp-control mt-1" /></label><button disabled={busy} className="h-10 self-end rounded-lg bg-blue-700 px-4 font-bold text-white">حفظ الميزانية والإنجاز</button></form>}
    <div className="rounded-xl bg-blue-50 p-3 text-sm leading-6 text-blue-950"><b>الخلاصة السريعة:</b> المصروف الفعلي يوضح ما حدث، والالتزامات توضح ما سنحتاج دفعه لاحقًا، أما المتوقع النهائي فهو تقدير تكلفة المشروع عند اكتمال نسبة الإنجاز المدخلة.</div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["الميزانية المعتمدة", f.budgetCents, "الحد المخطط للمشروع"],["التكلفة الفعلية", Object.values(data.planning.actualByCategory).reduce((a,b)=>a+b,0), "ما تم تسجيله كمصروف"],["مدفوعات منفذة", Math.max(0, Object.values(data.planning.actualByCategory).reduce((a,b)=>a+b,0) - data.planning.unpaidExecutedCents), "ما تم دفعه نقديًا"],["مستحقات منفذة", data.planning.unpaidExecutedCents, "منفذ ولم يُدفع بعد"],["التزامات مستقبلية", data.planning.commitmentsCents, "مرتبط بأعمال لم تُنفذ"],["المتوقع عند الانتهاء", f.finalCents, "حسب نسبة الإنجاز"],["المتبقي المتوقع", f.remainingCents, "ما قد نحتاج صرفه"],["الربح المتوقع", f.profitCents, "قيمة العقود ناقص المتوقع"]].map(([label,value,help])=><div key={String(label)} className="rounded-xl border bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 font-black text-blue-800">{cash(value as number|null)}</p><p className="mt-1 text-[11px] text-slate-400">{help}</p></div>)}</div>
    {(f.overrunCents ?? 0) > 0 && <p className="rounded-xl bg-red-50 p-3 font-bold text-red-700">تجاوز متوقع للميزانية: {cash(f.overrunCents)}</p>}{(f.commitmentGapCents ?? 0)>0 && <p className="rounded-xl bg-amber-50 p-3 font-bold text-amber-800">الالتزامات تتجاوز المتبقي المتوقع بمبلغ {cash(f.commitmentGapCents)}</p>}{f.completedWithCommitments && <p className="rounded-xl bg-amber-50 p-3 font-bold">الإنجاز 100% مع وجود التزامات متبقية؛ راجع البيانات.</p>}
    <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{["نوع التكلفة","الميزانية","الفعلي","الفرق"].map(x=><th key={x} className="p-2 text-right">{x}</th>)}</tr></thead><tbody>{(Object.keys(costCategories) as CostCategory[]).map(key=><tr key={key} className="border-t"><td className="p-2 font-bold">{costCategories[key]}</td><td className="p-2">{data.planning.budget ? cash(data.planning.budget[key]) : "لم تُسجل ميزانية"}</td><td className="p-2">{cash(data.planning.actualByCategory[key] || 0)}</td><td className="p-2">{data.planning.budget ? cash(data.planning.budget[key]-(data.planning.actualByCategory[key]||0)) : "—"}</td></tr>)}</tbody></table></div>
    <p className="text-sm">مستحقات منفذة غير مدفوعة: <b>{cash(data.planning.unpaidExecutedCents)}</b> · نسبة الإنجاز: <b>{data.planning.progressPercent == null ? "لم تسجل" : `${data.planning.progressPercent}% في ${data.planning.progressDate}`}</b></p>
    {canManage && <form onSubmit={saveCommitment} className="grid gap-3 rounded-xl border p-4 md:grid-cols-4"><input name="name" required minLength={2} placeholder="اسم الالتزام" className="erp-control"/><MoneyInput name="amount" placeholder="القيمة المتعاقد عليها" /><select name="sourceId" required className="erp-control"><option value="">اختر المقاولة أو فاتورة المورد</option>{data.planning.sources.filter(s=>!s.commitmentId).map(s=><option key={s.sourceType+s.sourceId} value={s.sourceId}>{s.partyName} · {s.name}</option>)}</select><button disabled={busy} className="rounded-lg bg-emerald-700 px-4 font-bold text-white">إضافة التزام</button></form>}
    <div className="space-y-2">{data.planning.commitments.map(item=><div key={item.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border p-3 text-sm"><b className={item.active ? "" : "text-slate-400 line-through"}>{item.name}</b><span>القيمة {cash(item.totalCents)} · المحقق {cash(item.realizedCents)} · المتبقي {cash(item.remainingCents)}</span>{canManage && item.active && <span className="flex items-center gap-2">{editingId === item.id ? <><input className="erp-control h-8 w-36" inputMode="decimal" value={editingValue} onChange={event => setEditingValue(event.target.value)} /><button type="button" className="text-emerald-700 underline" onClick={() => { const value = Number(editingValue.replaceAll(",", "")); if (Number.isFinite(value) && value >= 0) { void updateCommitment(item, true, Math.round(value * 100)); setEditingId(null); } }}>حفظ</button><button type="button" className="text-slate-600 underline" onClick={() => setEditingId(null)}>إلغاء</button></> : <><button type="button" className="text-blue-700 underline" onClick={() => { setEditingId(item.id); setEditingValue(String(item.totalCents / 100)); }}>تعديل القيمة</button><button type="button" className="text-red-700 underline" onClick={() => void updateCommitment(item, false)}>إلغاء الالتزام</button></>}</span>}</div>)}</div>
    {data.planning.history.length>0 && <details className="rounded-xl border p-3"><summary className="cursor-pointer font-bold">سجل تعديلات التخطيط</summary><div className="mt-3 space-y-2 text-xs">{data.planning.history.map(item=><p key={item.id}>{new Date(item.date).toLocaleString("ar-EG")} · {item.actor} · {item.action.endsWith("plan")?"تعديل الميزانية أو الإنجاز":"تعديل التزام"}</p>)}</div></details>}
  </section>;
}
