import Link from "next/link";
import { BanknoteArrowDown, BanknoteArrowUp, Building2, ChartNoAxesCombined, CircleAlert, FileSpreadsheet, Landmark, ShoppingCart, UsersRound, Vault } from "lucide-react";
import type { LucideIcon } from "lucide-react";

type Project = { id: string; name: string; owner: string; contractValue: string; incoming: string; cost: string; paid: string; margin: string; risk: string };
const moduleLinks = [
  { label: "الوارد", href: "/incoming", permission: "incoming.view", icon: BanknoteArrowUp }, { label: "مستخلصات المقاولين", href: "/expenses", permission: "expenses.view", icon: FileSpreadsheet }, { label: "المشتريات", href: "/purchases", permission: "purchases.view", icon: ShoppingCart }, { label: "Petty Cash", href: "/petty-cash", permission: "pettycash.view", icon: Vault }, { label: "المحاسبة", href: "/accounting", permission: "accounting.view", icon: Landmark }, { label: "المرتبات", href: "/salaries", permission: "salaries.view", icon: UsersRound },
];

export function RoleDashboard({ roleKey, roleName, userName, permissions, canFinancial, projects, totals }: { roleKey: string; roleName: string; userName: string; permissions: string[]; canFinancial: boolean; projects: Project[]; totals: Record<string, string> }) {
  const engineer = roleKey === "technical_office_engineer" || roleKey === "site_supervisor_engineer";
  const title = roleKey === "executive_director" ? "لوحة قيادة الشركة" : roleKey === "accountant" ? "المتابعة المالية اليومية" : engineer ? "متابعة مشروعاتي" : "لوحة إدارة النظام";
  const subtitle = engineer ? "تعرض هذه اللوحة المشروعات المسكن عليها حسابك فقط." : roleKey === "accountant" ? "تحصيلات، التزامات، وتكلفة المشروعات في مكان واحد." : "نظرة عملية تساعدك على اتخاذ القرار سريعًا.";
  const metrics: [string, string, LucideIcon, string][] = canFinancial ? [["قيمة العقود الواردة", totals.contractValue, Building2, "blue"], ["الوارد المحصل", totals.incoming, BanknoteArrowUp, "emerald"], ["تكلفة الأعمال", totals.cost, BanknoteArrowDown, "amber"], ["صافي السيولة", totals.liquidity, Landmark, "violet"]] : [["المشروعات المكلف بها", String(projects.length), Building2, "blue"], ["مستخلصات تحت الإجراء", "—", FileSpreadsheet, "amber"], ["حالة المتابعة", "جاهز", ChartNoAxesCombined, "emerald"], ["الوارد والماليات", "غير مسموح", Landmark, "slate"]];
  return <div className="space-y-6">
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold text-blue-700">{roleName}</p><h1 className="mt-2 text-2xl font-black text-slate-950 sm:text-3xl">{title} — {userName}</h1><p className="mt-2 text-sm text-slate-500">{subtitle}</p></div><Link href={engineer ? "/expenses" : "/project-cost-control"} className="inline-flex h-10 items-center gap-2 rounded-lg bg-blue-700 px-4 text-sm font-bold text-white hover:bg-blue-800">{engineer ? "فتح المستخلصات" : "موقف تكلفة المشروع"}<ChartNoAxesCombined className="size-4" /></Link></div></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label, value, Icon, tone]) => <article key={String(label)} className={`rounded-xl border bg-white p-4 shadow-sm ${tone === "emerald" ? "border-emerald-200" : tone === "amber" ? "border-amber-200" : tone === "violet" ? "border-violet-200" : "border-blue-200"}`}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-3 text-xl font-black text-blue-700" dir="ltr">{value}</p></div><span className="grid size-10 place-items-center rounded-xl bg-blue-50 text-blue-700"><Icon className="size-5" /></span></div></article>)}</section>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 p-5"><div><h2 className="font-black text-slate-900">{engineer ? "المشروعات المسكن عليها" : "أداء المشروعات"}</h2><p className="mt-1 text-xs text-slate-500">كل صف يفتح الملف المرتبط بالمشروع.</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600">{projects.length} مشروع</span></div><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-right text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-5 py-3">المشروع</th>{canFinancial && <><th className="px-5 py-3 text-center">العقود</th><th className="px-5 py-3 text-center">الوارد</th><th className="px-5 py-3 text-center">التكلفة</th><th className="px-5 py-3 text-center">الفرق</th></>}<th className="px-5 py-3">الحالة</th></tr></thead><tbody className="divide-y divide-slate-100">{projects.map((project) => <tr key={project.id}><td className="px-5 py-4"><Link href={`/expenses?project=${project.id}`} className="font-bold text-slate-900 hover:text-blue-700">{project.name}</Link><p className="mt-1 text-xs text-slate-400">{project.owner}{canFinancial && <> · <Link href={`/petty-cash?project=${project.id}`} className="font-bold text-blue-700 hover:underline">Petty Cash</Link></>}</p></td>{canFinancial && <><td className="px-5 py-4 text-center font-bold text-blue-700" dir="ltr">{project.contractValue}</td><td className="px-5 py-4 text-center font-bold text-emerald-700" dir="ltr">{project.incoming}</td><td className="px-5 py-4 text-center font-bold text-amber-700" dir="ltr">{project.cost}</td><td className="px-5 py-4 text-center font-bold text-slate-900" dir="ltr">{project.margin}</td></>}<td className="px-5 py-4"><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${project.risk === "ضمن المتاح" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{project.risk}</span></td></tr>)}{!projects.length && <tr><td colSpan={canFinancial ? 6 : 2} className="p-10 text-center text-sm text-slate-400"><CircleAlert className="mx-auto mb-2 size-5" />لا توجد مشروعات مربوطة بالحساب حاليًا.</td></tr>}</tbody></table></div></section>
    <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{moduleLinks.filter((item) => permissions.includes(item.permission)).map(({ label, href, icon: Icon }) => <Link key={href} href={href} className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-4 transition hover:-translate-y-0.5 hover:border-blue-200 hover:shadow-md"><span className="grid size-10 place-items-center rounded-xl bg-blue-50 text-blue-700"><Icon className="size-5" /></span><span className="font-bold text-slate-800">{label}</span></Link>)}</section>
  </div>;
}
