"use client";

import Link from "next/link";
import { Bar, BarChart, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { BanknoteArrowDown, BanknoteArrowUp, Building2, ChartNoAxesCombined, CircleAlert, FileSpreadsheet, Hand, Landmark, ShoppingCart, UsersRound, Vault } from "lucide-react";
import type { LucideIcon } from "lucide-react";

type Project = { id: string; name: string; owner: string; contractValue: string; incoming: string; cost: string; paid: string; margin: string; risk: string };
type Insights = { months: { key: string; label: string; incoming: number; cost: number }[]; costComposition: { name: string; value: number; color: string }[]; projectCount: number };

const moduleLinks = [
  { label: "الوارد", href: "/incoming", permission: "incoming.view", icon: BanknoteArrowUp },
  { label: "مستخلصات المقاولين", href: "/expenses", permission: "expenses.view", icon: FileSpreadsheet },
  { label: "المشتريات", href: "/purchases", permission: "purchases.view", icon: ShoppingCart },
  { label: "Petty Cash", href: "/petty-cash", permission: "pettycash.view", icon: Vault },
  { label: "المحاسبة", href: "/accounting", permission: "accounting.view", icon: Landmark },
  { label: "المرتبات", href: "/salaries", permission: "salaries.view", icon: UsersRound },
];

const chartNumber = new Intl.NumberFormat("ar-EG", { maximumFractionDigits: 0 });
const tooltipAmount = (value: unknown) => `${chartNumber.format(Number(Array.isArray(value) ? value[0] : value ?? 0) / 100)} ج.م`;

export function RoleDashboard({ roleKey, roleName, userName, permissions, canFinancial, projects, totals, insights }: { roleKey: string; roleName: string; userName: string; permissions: string[]; canFinancial: boolean; projects: Project[]; totals: Record<string, string>; insights?: Insights }) {
  const engineer = roleKey === "technical_office_engineer" || roleKey === "site_supervisor_engineer";
  const title = roleKey === "executive_director" ? "مركز قيادة الشركة" : roleKey === "accountant" ? "المتابعة المالية اليومية" : engineer ? "متابعة مشروعاتي" : "لوحة إدارة النظام";
  const subtitle = engineer ? "تعرض هذه اللوحة المشروعات المسكن عليها حسابك فقط." : roleKey === "accountant" ? "تحصيلات، التزامات، وتكلفة المشروعات في مكان واحد." : "صورة تشغيلية مختصرة تساعدك على اتخاذ القرار بسرعة.";
  const metrics: [string, string, LucideIcon, string][] = canFinancial
    ? [["قيمة العقود الواردة", totals.contractValue, Building2, "blue"], ["الوارد المحصل", totals.incoming, BanknoteArrowUp, "emerald"], ["تكلفة الأعمال", totals.cost, BanknoteArrowDown, "amber"], ["صافي السيولة", totals.liquidity, Landmark, "violet"]]
    : [["المشروعات المكلف بها", String(projects.length), Building2, "blue"], ["مستخلصات تحت الإجراء", "—", FileSpreadsheet, "amber"], ["حالة المتابعة", "جاهز", ChartNoAxesCombined, "emerald"], ["الوارد والماليات", "غير مسموح", Landmark, "slate"]];
  const pieData = insights?.costComposition.filter((item) => item.value > 0) ?? [];

  return <div className="space-y-6">
    <section className="relative overflow-hidden rounded-2xl border border-blue-100 bg-gradient-to-bl from-blue-50 via-white to-white p-6 shadow-sm">
      <div className="absolute -left-10 -top-16 size-48 rounded-full bg-blue-100/50 blur-3xl" />
      <div className="relative flex flex-wrap items-start justify-between gap-4"><div><div className="inline-flex items-center gap-2 rounded-full border border-blue-100 bg-white/90 px-3 py-1.5 text-xs font-bold text-blue-700"><Hand className="size-4" />مرحبًا، {userName}</div><p className="mt-3 text-xs font-bold text-blue-700">{roleName}</p><h1 className="mt-2 text-2xl font-black text-slate-950 sm:text-3xl">{title}</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">{subtitle}</p></div><Link href={engineer ? "/expenses" : "/project-cost-control"} className="inline-flex h-10 items-center gap-2 rounded-lg bg-blue-700 px-4 text-sm font-bold text-white shadow-md shadow-blue-200 transition hover:-translate-y-0.5 hover:bg-blue-800">{engineer ? "فتح المستخلصات" : "موقف تكلفة المشروع"}<ChartNoAxesCombined className="size-4" /></Link></div>
    </section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label, value, Icon, tone]) => <article key={String(label)} className={`rounded-xl border bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md ${tone === "emerald" ? "border-emerald-200" : tone === "amber" ? "border-amber-200" : tone === "violet" ? "border-violet-200" : "border-blue-200"}`}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-3 text-xl font-black text-blue-700" dir="ltr">{value}</p></div><span className={`grid size-10 place-items-center rounded-xl ${tone === "emerald" ? "bg-emerald-50 text-emerald-700" : tone === "amber" ? "bg-amber-50 text-amber-700" : tone === "violet" ? "bg-violet-50 text-violet-700" : "bg-blue-50 text-blue-700"}`}><Icon className="size-5" /></span></div></article>)}</section>
    {canFinancial && insights && <section className="grid gap-5 xl:grid-cols-[1.65fr_1fr]">
      <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4"><h2 className="font-black text-slate-900">تدفق الأموال</h2><p className="mt-1 text-xs text-slate-500">الوارد المحصل مقابل تكلفة الأعمال خلال آخر ستة أشهر.</p></div><div className="h-64" dir="ltr"><ResponsiveContainer width="100%" height="100%"><BarChart data={insights.months} margin={{ top: 8, right: 4, left: 4, bottom: 0 }}><XAxis dataKey="label" tick={{ fontSize: 11, fill: "#64748b" }} axisLine={false} tickLine={false} /><YAxis tickFormatter={(value) => `${chartNumber.format(value / 100)}`} tick={{ fontSize: 10, fill: "#94a3b8" }} width={52} axisLine={false} tickLine={false} /><Tooltip formatter={(value) => tooltipAmount(value)} labelStyle={{ color: "#0f172a", fontWeight: 700 }} contentStyle={{ borderRadius: 12, borderColor: "#e2e8f0", direction: "rtl" }} /><Legend verticalAlign="top" align="right" iconType="circle" wrapperStyle={{ fontSize: 12, paddingBottom: 10 }} /><Bar name="الوارد" dataKey="incoming" fill="#10b981" radius={[5, 5, 0, 0]} /><Bar name="التكلفة" dataKey="cost" fill="#2563eb" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></div></article>
      <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-black text-slate-900">مصدر كل جنيه تكلفة مسجل</h2><p className="mt-1 text-xs text-slate-500">تفصيل التكلفة المعتمدة الحالية.</p>{pieData.length ? <div className="mt-2 h-64" dir="ltr"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={pieData} dataKey="value" nameKey="name" innerRadius={57} outerRadius={84} paddingAngle={3}>{pieData.map((entry) => <Cell key={entry.name} fill={entry.color} />)}</Pie><Tooltip formatter={(value) => tooltipAmount(value)} contentStyle={{ borderRadius: 12, borderColor: "#e2e8f0", direction: "rtl" }} /></PieChart></ResponsiveContainer></div> : <div className="grid h-64 place-items-center text-center text-sm text-slate-400">لا توجد تكلفة معتمدة لعرض توزيعها بعد.</div>}<div className="flex flex-wrap justify-center gap-x-4 gap-y-2 text-xs font-bold text-slate-600">{pieData.map((item) => <span key={item.name} className="inline-flex items-center gap-1.5"><i className="size-2 rounded-full" style={{ backgroundColor: item.color }} />{item.name} {chartNumber.format(item.value / 100)} ج.م</span>)}</div></article>
    </section>}
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 p-5"><div><h2 className="font-black text-slate-900">{engineer ? "المشروعات المسكن عليها" : "أداء المشروعات"}</h2><p className="mt-1 text-xs text-slate-500">كل صف يفتح الملف المرتبط بالمشروع.</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600">{projects.length} مشروع</span></div><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-right text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-5 py-3">المشروع</th>{canFinancial && <><th className="px-5 py-3 text-center">العقود</th><th className="px-5 py-3 text-center">الوارد</th><th className="px-5 py-3 text-center">التكلفة</th><th className="px-5 py-3 text-center">الفرق</th></>}<th className="px-5 py-3">الحالة</th></tr></thead><tbody className="divide-y divide-slate-100">{projects.map((project) => <tr key={project.id}><td className="px-5 py-4"><Link href={`/expenses?project=${project.id}`} className="font-bold text-slate-900 hover:text-blue-700">{project.name}</Link><p className="mt-1 text-xs text-slate-400">{project.owner}{canFinancial && <> · <Link href={`/petty-cash?project=${project.id}`} className="font-bold text-blue-700 hover:underline">Petty Cash</Link></>}</p></td>{canFinancial && <><td className="px-5 py-4 text-center font-bold text-blue-700" dir="ltr">{project.contractValue}</td><td className="px-5 py-4 text-center font-bold text-emerald-700" dir="ltr">{project.incoming}</td><td className="px-5 py-4 text-center font-bold text-amber-700" dir="ltr">{project.cost}</td><td className="px-5 py-4 text-center font-bold text-slate-900" dir="ltr">{project.margin}</td></>}<td className="px-5 py-4"><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${project.risk === "ضمن المتاح" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{project.risk}</span></td></tr>)}{!projects.length && <tr><td colSpan={canFinancial ? 6 : 2} className="p-10 text-center text-sm text-slate-400"><CircleAlert className="mx-auto mb-2 size-5" />لا توجد مشروعات مربوطة بالحساب حاليًا.</td></tr>}</tbody></table></div></section>
    <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{moduleLinks.filter((item) => permissions.includes(item.permission)).map(({ label, href, icon: Icon }) => <Link key={href} href={href} className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-4 transition hover:-translate-y-0.5 hover:border-blue-200 hover:shadow-md"><span className="grid size-10 place-items-center rounded-xl bg-blue-50 text-blue-700"><Icon className="size-5" /></span><span className="font-bold text-slate-800">{label}</span></Link>)}</section>
  </div>;
}
