"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { CurrencyInput } from "@/components/currency-input";

type Employee = { id: string; employeeCode: string; name: string; jobTitle: string; monthlySalaryCents: number };
type Project = { id: string; name: string };
type Allocation = { id: string; employee: Employee; project: Project | null; startDate: Date; endDate: Date | null };
export function SalariesCenter({ employees, projects, allocations, canManage }: { employees: Employee[]; projects: Project[]; allocations: Allocation[]; canManage: boolean }) {
  const router = useRouter(); const [message, setMessage] = useState(""); const [busy, setBusy] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>, action: "salary" | "allocation") {
    event.preventDefault(); setBusy(action); setMessage("");
    const data = Object.fromEntries(new FormData(event.currentTarget));
    const body = action === "salary" ? { action, employeeId: data.employeeId, monthlySalaryCents: Math.round(Number(data.monthlySalaryCents || 0) * 100) } : { action, employeeId: data.employeeId, projectId: data.projectId || undefined, startDate: data.startDate, endDate: data.endDate || undefined };
    const response = await fetch("/api/salaries", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
    const result = await response.json(); setBusy(""); setMessage(response.ok ? "تم حفظ البيانات." : result.error || "تعذر الحفظ."); if (response.ok) { (event.currentTarget as HTMLFormElement).reset(); router.refresh(); }
  }
  const total = employees.reduce((sum, employee) => sum + employee.monthlySalaryCents, 0);
  return <div className="space-y-6"><section><p className="text-xs font-bold text-blue-700">Phase 8A · المرتبات</p><h1 className="mt-1 text-2xl font-black text-slate-950">الموظفون وتكلفة التسكين</h1><p className="mt-2 text-sm text-slate-500">الراتب الشهري ثابت، وتوزع التكلفة على المشروع حسب أيام التسكين الفعلية.</p></section>
    <div className="grid gap-3 sm:grid-cols-3"><Stat label="الموظفون النشطون" value={String(employees.length)} /><Stat label="إجمالي الالتزام الشهري" value={`${(total / 100).toLocaleString("en-US", { minimumFractionDigits: 2 })} ج.م`} /><Stat label="التكليفات المسجلة" value={String(allocations.length)} /></div>
    {message && <p className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm font-bold text-blue-800">{message}</p>}
    {canManage && <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-extrabold">تحديث الراتب الشهري</h2><form onSubmit={e => submit(e, "salary")} className="mt-4 space-y-3"><Select name="employeeId" label="الموظف" options={employees} /><label className="block"><span className="mb-1.5 block text-xs font-bold text-slate-600">الراتب الشهري</span><CurrencyInput name="monthlySalaryCents" required /></label><button disabled={busy === "salary"} className="h-11 rounded-lg bg-blue-600 px-5 text-sm font-bold text-white disabled:opacity-50">حفظ الراتب</button></form></section><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-extrabold">تسكين موظف على مشروع</h2><form onSubmit={e => submit(e, "allocation")} className="mt-4 grid gap-3 sm:grid-cols-2"><Select name="employeeId" label="الموظف" options={employees} /><Select name="projectId" label="المشروع" options={projects} optional /><label><span className="mb-1.5 block text-xs font-bold text-slate-600">من تاريخ</span><input name="startDate" type="date" required className="h-11 w-full rounded-lg border border-slate-200 px-3" /></label><label><span className="mb-1.5 block text-xs font-bold text-slate-600">إلى تاريخ (اختياري)</span><input name="endDate" type="date" className="h-11 w-full rounded-lg border border-slate-200 px-3" /></label><button disabled={busy === "allocation"} className="h-11 rounded-lg bg-blue-600 px-5 text-sm font-bold text-white sm:col-span-2 disabled:opacity-50">إضافة تسكين</button></form></section></div>}
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-extrabold">كشف الموظفين والتكلفة الشهرية</h2><p className="mt-1 text-xs text-slate-500">مرر على التسكين لمعرفة الفترة؛ استخدم النقر على الموبايل في الإصدار التالي.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-right text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{["الموظف", "المسمى", "المرتب الشهري", "المشروعات والتسكين", "الحالة"].map(h => <th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{employees.map(employee => { const rows = allocations.filter(a => a.employee.id === employee.id); return <tr key={employee.id}><td className="px-5 py-4 font-bold">{employee.name}<div className="text-xs text-slate-400">{employee.employeeCode}</div></td><td className="px-5 py-4 text-slate-600">{employee.jobTitle}</td><td className="px-5 py-4 font-bold text-blue-700">{(employee.monthlySalaryCents / 100).toLocaleString("en-US", { minimumFractionDigits: 2 })}</td><td className="px-5 py-4 text-slate-600">{rows.length ? rows.map(a => <span key={a.id} title={`${a.startDate.toISOString().slice(0, 10)} — ${a.endDate ? a.endDate.toISOString().slice(0, 10) : "مستمر"}`} className="ml-2 inline-block rounded-full bg-blue-50 px-2 py-1 text-xs">{a.project?.name || "عام الشركة"}</span>) : "عام الشركة"}</td><td className="px-5 py-4 text-emerald-700">نشط</td></tr>; })}</tbody></table></div></section>
  </div>;
}
function Select({ label, name, options, optional = false }: { label: string; name: string; options: { id: string; name: string }[]; optional?: boolean }) { return <label><span className="mb-1.5 block text-xs font-bold text-slate-600">{label}</span><select name={name} required={!optional} defaultValue="" className="h-11 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm">{optional && <option value="">عام الشركة</option>}{!optional && <option value="">اختر</option>}{options.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select></label>; }
function Stat({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-2 text-xl font-black text-slate-900">{value}</p></div>; }
