"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { CurrencyInput } from "@/components/currency-input";
import { UploadBox } from "@/components/upload-box";

type Employee = { id: string; employeeCode: string; name: string; jobTitle: string; monthlySalaryCents: number };
type Project = { id: string; name: string };
type Allocation = { id: string; employee: Employee; project: Project | null; startDate: Date; endDate: Date | null };
type Run = { id: string; month: string; status: string; totalCents: number; lines: { employee: Employee; netCents: number; allocationJson: string }[]; attachments: { id: string; name: string }[] };
type Advance = { id: string; employee: Employee; amountCents: number; remainingCents: number; repaymentMode: string; installmentCents: number | null; source: string; status: string };
export function SalariesCenter({ employees, projects, allocations, runs, advances, canManage }: { employees: Employee[]; projects: Project[]; allocations: Allocation[]; runs: Run[]; advances: Advance[]; canManage: boolean }) {
  const router = useRouter(); const [message, setMessage] = useState(""); const [busy, setBusy] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>, action: "salary" | "allocation") {
    event.preventDefault(); setBusy(action); setMessage("");
    const data = Object.fromEntries(new FormData(event.currentTarget));
    const body = action === "salary" ? { action, employeeId: data.employeeId, monthlySalaryCents: Math.round(Number(data.monthlySalaryCents || 0) * 100) } : { action, employeeId: data.employeeId, projectId: data.projectId || undefined, startDate: data.startDate, endDate: data.endDate || undefined };
    const response = await fetch("/api/salaries", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
    const result = await response.json(); setBusy(""); setMessage(response.ok ? "تم حفظ البيانات." : result.error || "تعذر الحفظ."); if (response.ok) { (event.currentTarget as HTMLFormElement).reset(); router.refresh(); }
  }
  async function operation(event: FormEvent<HTMLFormElement>, action: string) { event.preventDefault(); setBusy(action); setMessage(""); const form = event.currentTarget; const data = Object.fromEntries(new FormData(form)); const payload = { ...data }; const body = new FormData(); body.set("action", action); body.set("payload", JSON.stringify(payload)); for (const file of Array.from((form.querySelector('input[type="file"]') as HTMLInputElement)?.files || [])) body.append("files", file); const response = await fetch("/api/salaries", { method: "POST", body }); const result = await response.json(); setBusy(""); setMessage(response.ok ? "تم حفظ العملية." : result.error || "تعذر الحفظ."); if (response.ok) { form.reset(); router.refresh(); } }
  const total = employees.reduce((sum, employee) => sum + employee.monthlySalaryCents, 0);
  return <div className="space-y-6"><section><p className="text-xs font-bold text-blue-700">Phase 8A · المرتبات</p><h1 className="mt-1 text-2xl font-black text-slate-950">الموظفون وتكلفة التسكين</h1><p className="mt-2 text-sm text-slate-500">الراتب الشهري ثابت، وتوزع التكلفة على المشروع حسب أيام التسكين الفعلية.</p></section>
    <div className="grid gap-3 sm:grid-cols-3"><Stat label="الموظفون النشطون" value={String(employees.length)} /><Stat label="إجمالي الالتزام الشهري" value={`${(total / 100).toLocaleString("en-US", { minimumFractionDigits: 2 })} ج.م`} /><Stat label="التكليفات المسجلة" value={String(allocations.length)} /></div>
    {message && <p className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm font-bold text-blue-800">{message}</p>}
    {canManage && <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-extrabold">تحديث الراتب الشهري</h2><form onSubmit={e => submit(e, "salary")} className="mt-4 space-y-3"><Select name="employeeId" label="الموظف" options={employees} /><label className="block"><span className="mb-1.5 block text-xs font-bold text-slate-600">الراتب الشهري</span><CurrencyInput name="monthlySalaryCents" required /></label><button disabled={busy === "salary"} className="h-11 rounded-lg bg-blue-600 px-5 text-sm font-bold text-white disabled:opacity-50">حفظ الراتب</button></form></section><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-extrabold">تسكين موظف على مشروع</h2><form onSubmit={e => submit(e, "allocation")} className="mt-4 grid gap-3 sm:grid-cols-2"><Select name="employeeId" label="الموظف" options={employees} /><Select name="projectId" label="المشروع" options={projects} optional /><label><span className="mb-1.5 block text-xs font-bold text-slate-600">من تاريخ</span><input name="startDate" type="date" required className="h-11 w-full rounded-lg border border-slate-200 px-3" /></label><label><span className="mb-1.5 block text-xs font-bold text-slate-600">إلى تاريخ (اختياري)</span><input name="endDate" type="date" className="h-11 w-full rounded-lg border border-slate-200 px-3" /></label><button disabled={busy === "allocation"} className="h-11 rounded-lg bg-blue-600 px-5 text-sm font-bold text-white sm:col-span-2 disabled:opacity-50">إضافة تسكين</button></form></section></div>}
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-extrabold">كشف الموظفين والتكلفة الشهرية</h2><p className="mt-1 text-xs text-slate-500">التوزيع حسب أيام الشهر الفعلية؛ مرر أو انقر على التكليف لمعرفة مدته.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-right text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{["الموظف", "المسمى", "المرتب الشهري", "المشروعات والتسكين", "الحالة"].map(h => <th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{employees.map(employee => { const rows = allocations.filter(a => a.employee.id === employee.id); return <tr key={employee.id}><td className="px-5 py-4 font-bold">{employee.name}<div className="text-xs text-slate-400">{employee.employeeCode}</div></td><td className="px-5 py-4 text-slate-600">{employee.jobTitle}</td><td className="px-5 py-4 font-bold text-blue-700">{(employee.monthlySalaryCents / 100).toLocaleString("en-US", { minimumFractionDigits: 2 })}</td><td className="px-5 py-4 text-slate-600">{rows.length ? rows.map(a => <span key={a.id} title={`${a.startDate.toISOString().slice(0, 10)} — ${a.endDate ? a.endDate.toISOString().slice(0, 10) : "مستمر"}`} className="ml-2 inline-block rounded-full bg-blue-50 px-2 py-1 text-xs">{a.project?.name || "عام الشركة"}</span>) : "عام الشركة"}</td><td className="px-5 py-4 text-emerald-700">نشط</td></tr>; })}</tbody></table></div></section>
    {canManage && <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-extrabold">إنشاء واعتماد كشف شهر</h2><form onSubmit={e => operation(e, "create-payroll")} className="mt-4 space-y-3"><label className="block"><span className="mb-1.5 block text-xs font-bold text-slate-600">الشهر</span><input name="month" type="month" required className="h-11 w-full rounded-lg border border-slate-200 px-3" /></label><UploadBox name="files" label="مرفق كشف المرتبات" required multiple={false} /><button disabled={busy === "create-payroll"} className="h-11 rounded-lg bg-blue-600 px-5 text-sm font-bold text-white">إنشاء واعتماد الكشف</button></form></section><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-extrabold">إضافة سلفة</h2><form onSubmit={e => operation(e, "advance")} className="mt-4 grid gap-3 sm:grid-cols-2"><Select name="employeeId" label="الموظف" options={employees} /><label><span className="mb-1.5 block text-xs font-bold text-slate-600">القيمة</span><CurrencyInput name="amount" required /></label><Select name="repaymentMode" label="الاسترداد" options={[{id:"NEXT_PAYROLL",name:"المرتب القادم"},{id:"INSTALLMENTS",name:"أقساط"}]} /><label><span className="mb-1.5 block text-xs font-bold text-slate-600">قيمة القسط عند التقسيط</span><CurrencyInput name="installment" required={false} /></label><Select name="source" label="مصدر الصرف" options={[{id:"EXECUTIVE_DIRECTOR",name:"المدير التنفيذي"},{id:"PETTY_CASH",name:"Petty Cash"}]} /><label><span className="mb-1.5 block text-xs font-bold text-slate-600">تاريخ الصرف</span><input name="issuedAt" type="date" required className="h-11 w-full rounded-lg border border-slate-200 px-3" /></label><UploadBox name="files" label="إثبات السلفة" required multiple={false} /><button disabled={busy === "advance"} className="h-11 rounded-lg bg-blue-600 px-5 text-sm font-bold text-white sm:col-span-2">حفظ السلفة</button></form></section></div>}
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-extrabold">كشوف المرتبات</h2><div className="mt-4 space-y-2">{runs.length ? runs.map(run => <div key={run.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-100 p-3"><span className="font-bold">{run.month}</span><span>{(run.totalCents / 100).toLocaleString("en-US", { minimumFractionDigits: 2 })} ج.م</span><span className="text-xs text-slate-500">{run.status === "PAID" ? "مصروف من المدير التنفيذي" : "معتمد — جاهز للصرف"}</span>{canManage && run.status === "APPROVED" && <button onClick={() => { const f = new FormData(); f.set("action", "payroll-pay"); f.set("payload", JSON.stringify({ id: run.id })); fetch("/api/salaries", { method: "POST", body: f }).then(() => router.refresh()); }} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white">تسجيل صرف المدير التنفيذي</button>}</div>) : <p className="text-sm text-slate-500">لا توجد كشوف بعد.</p>}</div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-extrabold">السلف القائمة</h2><div className="mt-4 space-y-2">{advances.length ? advances.map(a => <div key={a.id} className="flex flex-wrap justify-between gap-2 rounded-xl border border-slate-100 p-3 text-sm"><span className="font-bold">{a.employee.name}</span><span>متبقي {(a.remainingCents / 100).toLocaleString("en-US", { minimumFractionDigits: 2 })} ج.م</span><span className="text-slate-500">{a.repaymentMode === "INSTALLMENTS" ? "أقساط" : "المرتب القادم"} · {a.source === "PETTY_CASH" ? "Petty Cash" : "المدير التنفيذي"}</span></div>) : <p className="text-sm text-slate-500">لا توجد سلف قائمة.</p>}</div></section>
  </div>;
}
function Select({ label, name, options, optional = false }: { label: string; name: string; options: { id: string; name: string }[]; optional?: boolean }) { return <label><span className="mb-1.5 block text-xs font-bold text-slate-600">{label}</span><select name={name} required={!optional} defaultValue="" className="h-11 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm">{optional && <option value="">عام الشركة</option>}{!optional && <option value="">اختر</option>}{options.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select></label>; }
function Stat({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-2 text-xl font-black text-slate-900">{value}</p></div>; }
