"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeftRight, Boxes, ClipboardCheck, PackageCheck, Plus, ReceiptText, Send, X } from "lucide-react";
import { ERPSelect } from "@/components/erp-select";
import { KpiCard, MoneyValue } from "@/components/erp-ui";
import { pdfColumns, pdfMoney, previewDataPdf, usePdfDataExport } from "@/components/pdf-data-export";

type Initial = Awaited<ReturnType<typeof import("@/lib/warehouse").warehouseSnapshot>>;
type Tab = "stock" | "receipts" | "operations" | "count" | "ledger";
type Modal = "item" | "issue" | "return" | "transfer" | "count" | "receipt" | null;
type FormLine = { key: string; itemId: string; quantity: number };
const today = () => new Date().toLocaleDateString("en-CA", { timeZone: "Africa/Cairo" });
const money = (cents: number) => (cents / 100).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const movementLabel: Record<string, string> = { RECEIPT: "استلام من مورد", ISSUE_PROJECT: "صرف لمشروع", RETURN_PROJECT: "مرتجع مشروع", TRANSFER: "تحويل بين مخازن", ADJUSTMENT_IN: "زيادة جرد", ADJUSTMENT_OUT: "عجز جرد" };

export function WarehouseCenter({ initial, canManage }: { initial: Initial; canManage: boolean }) {
  const router = useRouter();
  const [tab, setTab] = useState<Tab>("stock");
  const [modal, setModal] = useState<Modal>(null);
  const [selectedInvoice, setSelectedInvoice] = useState("");
  const [lines, setLines] = useState<FormLine[]>([{ key: crypto.randomUUID(), itemId: "", quantity: 1 }]);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [search, setSearch] = useState("");
  const [warehouseId, setWarehouseId] = useState(initial.warehouses[0]?.id || "");
  const itemMap = useMemo(() => new Map(initial.items.map((item) => [item.id, item])), [initial.items]);
  const warehouseMap = useMemo(() => new Map(initial.warehouses.map((item) => [item.id, item])), [initial.warehouses]);
  const projectMap = useMemo(() => new Map(initial.projects.map((item) => [item.id, item])), [initial.projects]);
  const stockRows = useMemo(() => initial.balances.map((balance) => ({ ...balance, item: itemMap.get(balance.itemId), warehouse: warehouseMap.get(balance.warehouseId) })).filter((row) => row.item && row.warehouse && (!warehouseId || row.warehouseId === warehouseId) && `${row.item?.name} ${row.item?.code}`.toLowerCase().includes(search.toLowerCase())), [initial.balances, itemMap, warehouseMap, warehouseId, search]);
  const availableRows = stockRows.filter((row) => row.quantity > 0.000001);
  const stockValue = availableRows.reduce((sum, row) => sum + row.valueCents, 0);
  const lowStock = availableRows.filter((row) => row.item && row.item.minimumQuantity > 0 && row.quantity <= row.item.minimumQuantity).length;
  const pendingInvoices = initial.invoices.filter((invoice) => invoice.items.some((item) => item.quantity - Number(initial.receivedByPurchaseItem[item.id] || 0) > 0.000001));
  const tabs: [Tab, string][] = [["stock", "الأصناف والأرصدة"], ["receipts", "الاستلامات"], ["operations", "الصرف والتحويل"], ["count", "الجرد"], ["ledger", "سجل الحركات"]];

  usePdfDataExport(() => void previewDataPdf({
    title: "تقرير المخزن",
    filters: warehouseId ? warehouseMap.get(warehouseId)?.name : "كل المخازن",
    kpis: [{ label: "قيمة الرصيد", value: pdfMoney(stockValue), tone: "blue" }, { label: "الأصناف المتاحة", value: String(availableRows.length), tone: "emerald" }, { label: "استلامات منتظرة", value: String(pendingInvoices.length), tone: "amber" }, { label: "تحت الحد الأدنى", value: String(lowStock), tone: "violet" }],
    tables: [{ columns: pdfColumns(["الكود", 2], ["الصنف", 3], ["المخزن", 2], ["الكمية", 2], ["متوسط التكلفة", 2], ["قيمة الرصيد", 2]), rows: stockRows.map((row) => [row.item!.code, row.item!.name, row.warehouse!.name, `${row.quantity.toLocaleString("en-US")} ${row.item!.unit}`, pdfMoney(row.averageCostCents), pdfMoney(row.valueCents)]) }],
  }));

  function open(kind: Exclude<Modal, null>, invoiceId = "") { setModal(kind); setSelectedInvoice(invoiceId); setError(""); setLines([{ key: crypto.randomUUID(), itemId: "", quantity: 1 }]); }
  async function send(payload: Record<string, unknown>) {
    setBusy(true); setError("");
    try { const response = await fetch("/api/warehouse", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "تعذر حفظ الحركة."); setModal(null); router.refresh(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "تعذر حفظ الحركة."); }
    finally { setBusy(false); }
  }
  function addLine() { setLines((current) => [...current, { key: crypto.randomUUID(), itemId: "", quantity: 1 }]); }
  function patchLine(key: string, patch: Partial<FormLine>) { setLines((current) => current.map((row) => row.key === key ? { ...row, ...patch } : row)); }
  const selected = initial.invoices.find((invoice) => invoice.id === selectedInvoice);

  return <div className="space-y-5">
    <section className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold text-blue-700">Warehouse Module</p><h1 className="mt-1 text-2xl font-black text-slate-950">المخزن وحركة الخامات</h1><p className="mt-2 text-sm text-slate-500">الاستلام يزيد الرصيد، والصرف للمشروع هو الذي يحمّل تكلفة الخامات.</p></div>{canManage && <div className="flex flex-wrap gap-2"><button type="button" className="erp-back-tab" onClick={() => open("item")}><Plus className="size-4" />صنف جديد</button><button type="button" className="inline-flex items-center gap-2 rounded-lg bg-blue-700 px-4 py-2 text-sm font-bold text-white" onClick={() => open("issue")}><Send className="size-4" />صرف لمشروع</button></div>}</section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="قيمة المخزون الحالي" value={`${money(stockValue)} ج.م`} icon={Boxes} tone="blue" /><KpiCard label="أصناف برصيد متاح" value={String(availableRows.length)} icon={PackageCheck} tone="emerald" /><KpiCard label="استلامات منتظرة" value={String(pendingInvoices.length)} icon={ReceiptText} tone="amber" /><KpiCard label="عند/تحت الحد الأدنى" value={String(lowStock)} icon={ClipboardCheck} tone="violet" /></section>
    <nav className="flex flex-wrap gap-2 rounded-xl border bg-white p-2" aria-label="أقسام المخزن">{tabs.map(([key, label]) => <button key={key} type="button" onClick={() => setTab(key)} className={`rounded-lg px-4 py-2 text-sm font-bold ${tab === key ? "bg-blue-700 text-white" : "text-slate-600 hover:bg-slate-100"}`}>{label}</button>)}</nav>
    {tab === "stock" && <section className="erp-table-shell"><div className="grid gap-3 border-b bg-white p-4 md:grid-cols-2"><label className="grid gap-1 text-xs font-bold">المخزن<ERPSelect value={warehouseId} onValueChange={setWarehouseId}><option value="">كل المخازن</option>{initial.warehouses.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</ERPSelect></label><label className="grid gap-1 text-xs font-bold">بحث عن صنف<input className="erp-control" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="اسم الصنف أو الكود..." /></label></div><div className="erp-table-scroll"><table className="erp-data-table min-w-[850px]"><thead><tr>{["الكود", "الصنف", "المخزن", "الكمية المتاحة", "متوسط التكلفة", "قيمة الرصيد", "الحالة"].map((head) => <th key={head}>{head}</th>)}</tr></thead><tbody>{stockRows.map((row) => <tr key={`${row.warehouseId}:${row.itemId}`}><td>{row.item!.code}</td><td><b>{row.item!.name}</b><p className="text-xs text-slate-400">{row.item!.category || "غير مصنف"} · {row.item!.unit}</p></td><td>{row.warehouse!.name}</td><td><b dir="ltr">{row.quantity.toLocaleString("en-US")} {row.item!.unit}</b></td><td><MoneyValue>{money(row.averageCostCents)} ج.م</MoneyValue></td><td><MoneyValue>{money(row.valueCents)} ج.م</MoneyValue></td><td>{row.quantity <= 0 ? <span className="rounded-full bg-rose-50 px-2 py-1 text-xs font-bold text-rose-700">نفد</span> : row.item!.minimumQuantity > 0 && row.quantity <= row.item!.minimumQuantity ? <span className="rounded-full bg-amber-50 px-2 py-1 text-xs font-bold text-amber-700">إعادة طلب</span> : <span className="rounded-full bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-700">متاح</span>}</td></tr>)}{!stockRows.length && <tr><td colSpan={7} className="p-10 text-center text-slate-400">لا يوجد رصيد في الاختيارات الحالية. استخدم الاستلامات أو الجرد الافتتاحي لإضافة الرصيد.</td></tr>}</tbody></table></div></section>}
    {tab === "receipts" && <section className="space-y-3">{pendingInvoices.map((invoice) => <article key={invoice.id} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs text-slate-500">{invoice.number} · {invoice.invoiceDate.slice(0, 10)}</p><h2 className="mt-1 font-black">{invoice.name}</h2><p className="mt-1 text-xs text-slate-500">{invoice.supplier?.name || "مورد غير محدد"} · المشروع: {invoice.project.name}</p></div>{canManage && <button type="button" className="rounded-lg bg-blue-700 px-4 py-2 text-xs font-bold text-white" onClick={() => open("receipt", invoice.id)}>استلام الخامات</button>}</div><div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{invoice.items.map((item) => { const got = Number(initial.receivedByPurchaseItem[item.id] || 0); return <div key={item.id} className="rounded-lg border bg-slate-50 px-3 py-2 text-xs"><div className="flex justify-between gap-2 font-bold"><span>{item.name}</span><span>{item.quantity} {item.unit}</span></div><p className="mt-1 text-slate-500">استُلم {got} · متبقي {Math.max(0, item.quantity - got)}</p></div>; })}</div></article>)}{!pendingInvoices.length && <div className="rounded-2xl border bg-white p-12 text-center text-slate-400">لا توجد فواتير مخزنية تنتظر الاستلام.</div>}</section>}
    {tab === "operations" && <section className="grid gap-4 md:grid-cols-3"><button disabled={!canManage} type="button" onClick={() => open("issue")} className="rounded-2xl border bg-white p-6 text-start shadow-sm hover:border-blue-300"><Send className="size-8 text-blue-700" /><h2 className="mt-4 font-black">صرف خامات لمشروع</h2><p className="mt-2 text-sm text-slate-500">يخفض رصيد المخزن ويحمّل قيمة الخامات على تكلفة المشروع فورًا.</p></button><button disabled={!canManage} type="button" onClick={() => open("return")} className="rounded-2xl border bg-white p-6 text-start shadow-sm hover:border-emerald-300"><PackageCheck className="size-8 text-emerald-700" /><h2 className="mt-4 font-black">مرتجع من مشروع</h2><p className="mt-2 text-sm text-slate-500">يعيد المتبقي للمخزن ويخفض تكلفة الخامات المحملة على المشروع.</p></button><button disabled={!canManage || initial.warehouses.length < 2} type="button" onClick={() => open("transfer")} className="rounded-2xl border bg-white p-6 text-start shadow-sm hover:border-blue-300 disabled:opacity-50"><ArrowLeftRight className="size-8 text-violet-700" /><h2 className="mt-4 font-black">تحويل بين مخازن الشركة</h2><p className="mt-2 text-sm text-slate-500">يغيّر مكان الرصيد فقط ولا يحمّل أي مشروع بتكلفة.</p></button></section>}
    {tab === "count" && <section className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-white p-4"><div><h2 className="font-black">الجرد والتسويات</h2><p className="mt-1 text-xs text-slate-500">سجّل الكمية الفعلية؛ النظام ينشئ حركة موثقة بالفرق بدل تعديل الرصيد بصمت.</p></div>{canManage && <button type="button" onClick={() => open("count")} className="rounded-lg bg-blue-700 px-4 py-2 text-xs font-bold text-white">بدء جرد</button>}</div>{initial.counts.map((count) => <article key={count.id} className="rounded-xl border bg-white p-4"><div className="flex justify-between gap-3"><div><b>{count.number}</b><p className="text-xs text-slate-500">{count.warehouse.name} · {count.countDate.slice(0, 10)}</p></div><span className="rounded-full bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-700">معتمد</span></div><p className="mt-3 text-xs text-slate-600">{count.lines.length} صنف · فروق في {count.lines.filter((line) => Math.abs(line.difference) > 0.000001).length} صنف</p></article>)}{!initial.counts.length && <div className="rounded-xl border bg-white p-10 text-center text-slate-400">لم يُسجل جرد بعد.</div>}</section>}
    {tab === "ledger" && <section className="erp-table-shell"><div className="erp-table-scroll"><table className="erp-data-table min-w-[950px]"><thead><tr>{["التاريخ", "رقم الحركة", "النوع", "من / إلى", "الصنف", "الكمية", "القيمة", "المستلم"].map((head) => <th key={head}>{head}</th>)}</tr></thead><tbody>{initial.movements.flatMap((movement) => movement.lines.map((line) => <tr key={line.id}><td dir="ltr">{movement.movementDate.slice(0, 10)}</td><td>{movement.number}</td><td>{movementLabel[movement.type] || movement.type}</td><td>{movement.type === "ISSUE_PROJECT" || movement.type === "RETURN_PROJECT" ? projectMap.get(movement.projectId || "")?.name || "مشروع" : `${movement.fromWarehouse?.name || "المورد/الجرد"} ← ${movement.toWarehouse?.name || "المشروع/الجرد"}`}</td><td className="font-bold">{line.item.name}</td><td dir="ltr">{line.quantity} {line.item.unit}</td><td><MoneyValue>{money(line.totalCents)} ج.م</MoneyValue></td><td>{movement.recipient || "—"}</td></tr>))}{!initial.movements.length && <tr><td colSpan={8} className="p-10 text-center text-slate-400">لا توجد حركات مخزنية بعد.</td></tr>}</tbody></table></div></section>}
    {modal && <ModalShell title={modal === "item" ? "إضافة صنف مخزني" : modal === "receipt" ? "استلام فاتورة مشتريات" : modal === "issue" ? "صرف خامات لمشروع" : modal === "return" ? "مرتجع خامات من مشروع" : modal === "transfer" ? "تحويل بين المخازن" : "جرد فعلي"} onClose={() => setModal(null)}>
      {modal === "item" ? <form className="space-y-3" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void send({ action: "item", name: form.get("name"), unit: form.get("unit"), category: form.get("category"), minimumQuantity: Number(form.get("minimumQuantity")) }); }}><label className="grid gap-1 text-xs font-bold">اسم الصنف *<input name="name" required className="erp-control" /></label><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-xs font-bold">الوحدة *<input name="unit" required className="erp-control" placeholder="طن / كيس / متر" /></label><label className="grid gap-1 text-xs font-bold">حد إعادة الطلب<input name="minimumQuantity" type="number" min="0" step="0.001" defaultValue="0" className="erp-control" /></label></div><label className="grid gap-1 text-xs font-bold">التصنيف<input name="category" className="erp-control" placeholder="أسمنت / حديد / تشطيبات" /></label><Submit busy={busy} /></form>
      : modal === "receipt" && selected ? <ReceiptForm invoice={selected} warehouses={initial.warehouses} projects={initial.projects} received={initial.receivedByPurchaseItem} busy={busy} error={error} onSubmit={send} />
      : modal === "count" ? <CountForm warehouses={initial.warehouses} items={initial.items} balances={initial.balances} busy={busy} error={error} onSubmit={send} />
      : <form className="space-y-4" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const common = { movementDate: form.get("date"), recipient: form.get("recipient"), notes: form.get("notes"), lines: lines.filter((row) => row.itemId && row.quantity > 0).map(({ itemId, quantity }) => ({ itemId, quantity })) }; void send(modal === "issue" ? { action: "issue", warehouseId: form.get("warehouseId"), projectId: form.get("projectId"), ...common } : modal === "return" ? { action: "return", warehouseId: form.get("warehouseId"), projectId: form.get("projectId"), ...common } : { action: "transfer", fromWarehouseId: form.get("warehouseId"), toWarehouseId: form.get("toWarehouseId"), ...common }); }}><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-xs font-bold">{modal === "return" ? "إلى المخزن *" : "من المخزن *"}<ERPSelect name="warehouseId" required>{initial.warehouses.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</ERPSelect></label>{modal === "issue" || modal === "return" ? <label className="grid gap-1 text-xs font-bold">المشروع *<ERPSelect name="projectId" required><option value="">اختر المشروع</option>{initial.projects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</ERPSelect></label> : <label className="grid gap-1 text-xs font-bold">إلى المخزن *<ERPSelect name="toWarehouseId" required><option value="">اختر المخزن</option>{initial.warehouses.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</ERPSelect></label>}<label className="grid gap-1 text-xs font-bold">التاريخ *<input name="date" type="date" required defaultValue={today()} className="erp-control" /></label><label className="grid gap-1 text-xs font-bold">المستلم *<input name="recipient" required className="erp-control" /></label></div><MovementLines lines={lines} items={initial.items} onPatch={patchLine} onAdd={addLine} /><label className="grid gap-1 text-xs font-bold">ملاحظات<textarea name="notes" className="erp-control" rows={2} /></label>{error && <p className="rounded-lg bg-rose-50 p-3 text-xs font-bold text-rose-700">{error}</p>}<Submit busy={busy} /></form>}
    </ModalShell>}
  </div>;
}

function ModalShell({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><section role="dialog" aria-modal="true" className="max-h-[90vh] w-full max-w-3xl overflow-auto rounded-2xl border bg-white p-5 shadow-2xl"><div className="mb-5 flex items-center justify-between gap-3 border-b pb-3"><h2 className="text-lg font-black">{title}</h2><button type="button" onClick={onClose} aria-label="إغلاق" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><X className="size-5" /></button></div>{children}</section></div>; }
function Submit({ busy }: { busy: boolean }) { return <button disabled={busy} className="w-full rounded-lg bg-blue-700 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{busy ? "جارٍ الحفظ…" : "تأكيد وحفظ"}</button>; }
function MovementLines({ lines, items, onPatch, onAdd }: { lines: FormLine[]; items: Initial["items"]; onPatch: (key: string, patch: Partial<FormLine>) => void; onAdd: () => void }) { return <section className="rounded-xl border"><div className="flex items-center justify-between border-b bg-slate-50 p-3"><b className="text-sm">بنود الحركة</b><button type="button" onClick={onAdd} className="text-xs font-bold text-blue-700">+ إضافة بند</button></div><div className="divide-y">{lines.map((line) => <div key={line.key} className="grid gap-3 p-3 sm:grid-cols-[1fr_160px]"><label className="grid gap-1 text-xs font-bold">الصنف<ERPSelect value={line.itemId} onValueChange={(value) => onPatch(line.key, { itemId: value })}><option value="">اختر الصنف</option>{items.map((item) => <option key={item.id} value={item.id}>{item.code} — {item.name} ({item.unit})</option>)}</ERPSelect></label><label className="grid gap-1 text-xs font-bold">الكمية<input type="number" min="0.000001" step="0.001" value={line.quantity} onChange={(event) => onPatch(line.key, { quantity: Number(event.target.value) })} className="erp-control" /></label></div>)}</div></section>; }

function ReceiptForm({ invoice, warehouses, projects, received, busy, error, onSubmit }: { invoice: Initial["invoices"][number]; warehouses: Initial["warehouses"]; projects: Initial["projects"]; received: Initial["receivedByPurchaseItem"]; busy: boolean; error: string; onSubmit: (payload: Record<string, unknown>) => Promise<void> }) {
  const remaining = invoice.items.map((item) => ({ item, quantity: Math.max(0, item.quantity - Number(received[item.id] || 0)) })).filter((row) => row.quantity > 0.000001);
  const [quantities, setQuantities] = useState(() => Object.fromEntries(remaining.map((row) => [row.item.id, row.quantity])));
  const [direct, setDirect] = useState(false);
  return <form className="space-y-4" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void onSubmit({ action: "receipt", invoiceId: invoice.id, warehouseId: form.get("warehouseId"), movementDate: form.get("date"), recipient: form.get("recipient"), notes: form.get("notes"), directProjectId: direct ? form.get("projectId") : undefined, lines: remaining.filter((row) => Number(quantities[row.item.id]) > 0).map((row) => ({ purchaseItemId: row.item.id, quantity: Number(quantities[row.item.id]) })) }); }}><div className="rounded-xl bg-blue-50 p-3"><b>{invoice.number} · {invoice.name}</b><p className="mt-1 text-xs text-slate-600">{invoice.supplier?.name || "مورد غير محدد"} · {invoice.project.name}</p></div><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-xs font-bold">المخزن *<ERPSelect name="warehouseId" required>{warehouses.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</ERPSelect></label><label className="grid gap-1 text-xs font-bold">تاريخ الاستلام *<input name="date" type="date" required defaultValue={today()} className="erp-control" /></label><label className="grid gap-1 text-xs font-bold">المستلم *<input name="recipient" required className="erp-control" /></label></div><section className="rounded-xl border"><div className="border-b bg-slate-50 p-3 text-sm font-bold">الكميات المستلمة</div>{remaining.map(({ item, quantity }) => <label key={item.id} className="grid grid-cols-[1fr_140px] items-center gap-3 border-b p-3 text-xs last:border-0"><span><b>{item.name}</b><small className="block text-slate-500">المتبقي {quantity} {item.unit}</small></span><input type="number" min="0" max={quantity} step="0.001" value={quantities[item.id]} onChange={(event) => setQuantities((current) => ({ ...current, [item.id]: Number(event.target.value) }))} className="erp-control" /></label>)}</section><label className="flex cursor-pointer items-center gap-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm font-bold"><input type="checkbox" checked={direct} onChange={(event) => setDirect(event.target.checked)} />استلام وصرف الكميات نفسها مباشرة على مشروع</label>{direct && <label className="grid gap-1 text-xs font-bold">المشروع المستفيد *<ERPSelect name="projectId" required><option value="">اختر المشروع</option>{projects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</ERPSelect></label>}<label className="grid gap-1 text-xs font-bold">ملاحظات<textarea name="notes" className="erp-control" rows={2} /></label>{error && <p className="rounded-lg bg-rose-50 p-3 text-xs font-bold text-rose-700">{error}</p>}<Submit busy={busy} /></form>;
}

function CountForm({ warehouses, items, balances, busy, error, onSubmit }: { warehouses: Initial["warehouses"]; items: Initial["items"]; balances: Initial["balances"]; busy: boolean; error: string; onSubmit: (payload: Record<string, unknown>) => Promise<void> }) {
  const [warehouseId, setWarehouseId] = useState(warehouses[0]?.id || ""); const [actual, setActual] = useState<Record<string, number>>({});
  const rows = items.map((item) => ({ item, book: balances.find((row) => row.warehouseId === warehouseId && row.itemId === item.id)?.quantity || 0 })).filter((row) => row.book || actual[row.item.id] !== undefined);
  return <form className="space-y-4" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void onSubmit({ action: "count", warehouseId, countDate: form.get("date"), notes: form.get("notes"), lines: rows.map((row) => ({ itemId: row.item.id, actualQuantity: actual[row.item.id] ?? row.book, reason: "جرد فعلي" })) }); }}><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-xs font-bold">المخزن *<ERPSelect value={warehouseId} onValueChange={setWarehouseId}>{warehouses.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</ERPSelect></label><label className="grid gap-1 text-xs font-bold">تاريخ الجرد *<input name="date" type="date" required defaultValue={today()} className="erp-control" /></label></div><div className="max-h-80 overflow-auto rounded-xl border"><table className="erp-data-table"><thead><tr><th>الصنف</th><th>كمية النظام</th><th>الكمية المعدودة</th><th>الفرق</th></tr></thead><tbody>{rows.map(({ item, book }) => { const counted = actual[item.id] ?? book; return <tr key={item.id}><td className="font-bold">{item.name}</td><td>{book} {item.unit}</td><td><input aria-label={`الكمية المعدودة ${item.name}`} type="number" min="0" step="0.001" value={counted} onChange={(event) => setActual((current) => ({ ...current, [item.id]: Number(event.target.value) }))} className="erp-control !w-32" /></td><td className={counted - book ? "font-bold text-rose-700" : "text-slate-400"}>{counted - book}</td></tr>; })}</tbody></table></div><label className="grid gap-1 text-xs font-bold">ملاحظات الجرد<textarea name="notes" className="erp-control" rows={2} /></label>{error && <p className="rounded-lg bg-rose-50 p-3 text-xs font-bold text-rose-700">{error}</p>}<Submit busy={busy} /></form>;
}
