import { spawnSync } from "node:child_process";
import { access, mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const mode = process.argv[2] || "prepare";
const sourceSchema = resolve(root, "prisma/schema.prisma");
const postgresRoot = resolve(root, "prisma/postgresql");
const postgresSchema = resolve(postgresRoot, "schema.prisma");
const migrationName = "20260924000000_initial_schema";
const migrationDir = resolve(postgresRoot, "migrations", migrationName);
const migrationFile = resolve(migrationDir, "migration.sql");
const lockFile = resolve(postgresRoot, "migrations/migration_lock.toml");
const prismaCli = resolve(root, "node_modules/prisma/build/index.js");
const localValidateUrl = "postgresql://schema-validation-only:schema-validation-only@localhost:5432/schema-validation?schema=public";

function runPrisma(args, env = process.env, quiet = false) {
  const result = spawnSync(process.execPath, [prismaCli, ...args], { cwd: root, env, encoding: "utf8", maxBuffer: 16 * 1024 * 1024 });
  if (!quiet && result.stdout) process.stdout.write(result.stdout);
  if (result.stderr) process.stderr.write(result.stderr);
  if (result.status !== 0) throw new Error(`أمر Prisma فشل برمز ${result.status ?? "غير معروف"}.`);
  return result.stdout || "";
}

async function prepare() {
  const sqliteSchema = await readFile(sourceSchema, "utf8");
  const matches = sqliteSchema.match(/provider\s*=\s*"sqlite"/g) || [];
  if (matches.length !== 1) throw new Error("لم أجد موفر SQLite واحدًا واضحًا في المخطط الحالي؛ أوقف تجهيز PostgreSQL للمراجعة.");
  const pgSchema = sqliteSchema.replace('provider = "sqlite"', 'provider = "postgresql"');
  await mkdir(dirname(postgresSchema), { recursive: true });

  try {
    const currentSchema = await readFile(postgresSchema, "utf8");
    if (currentSchema !== pgSchema) throw new Error("مخطط PostgreSQL موجود لكنه لا يطابق المخطط الحالي. لم يتم استبدال أي ترحيل؛ يلزم إنشاء ترحيل إضافي مُراجع.");
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
    await writeFile(postgresSchema, pgSchema, "utf8");
  }

  await access(prismaCli);
  await mkdir(migrationDir, { recursive: true });
  const migrationSql = runPrisma(["migrate", "diff", "--from-empty", "--to-schema-datamodel", postgresSchema, "--script"], { ...process.env, DATABASE_URL: localValidateUrl }, true);
  if (!migrationSql.includes('CREATE TABLE "User"')) throw new Error("ناتج PostgreSQL لا يحتوي على مخطط النظام المتوقع.");
  let initialMigrationExists = false;
  try {
    const existing = await readFile(migrationFile, "utf8");
    initialMigrationExists = true;
    if (!existing.includes('CREATE TABLE "User"')) throw new Error("الترحيل الابتدائي الموجود لا يحتوي على مخطط النظام المتوقع.");
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
    await writeFile(migrationFile, migrationSql, "utf8");
  }
  if (initialMigrationExists) {
    const migrationEntries = (await readdir(resolve(postgresRoot, "migrations"), { withFileTypes: true }))
      .filter((entry) => entry.isDirectory() && entry.name !== migrationName)
      .map((entry) => entry.name)
      .sort();
    const incrementalSql = (await Promise.all(migrationEntries.map((name) => readFile(resolve(postgresRoot, "migrations", name, "migration.sql"), "utf8")))).join("\n");
    for (const fragment of ['ADD COLUMN "paidCents"', 'ADD COLUMN "paymentTrackingStarted"', 'CREATE TABLE "PurchasePayment"']) {
      if (!incrementalSql.includes(fragment)) throw new Error(`مخطط PostgreSQL الحالي يحتاج migration إضافية مفقودة: ${fragment}`);
    }
    console.log("الترحيل الابتدائي موجود ومحفوظ؛ تغييرات دفعات الموردين مغطاة بترحيل إضافي ولم يتم استبدال سجل الترحيلات.");
  }
  try {
    const existingLock = await readFile(lockFile, "utf8");
    if (!existingLock.includes('provider = "postgresql"')) throw new Error("ملف قفل الترحيلات الموجود لا يطابق PostgreSQL.");
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
    await writeFile(lockFile, '# Please do not edit this file manually\nprovider = "postgresql"\n', "utf8");
  }
  console.log("مخطط PostgreSQL مطابق لمخطط Prisma الحالي، وملفات الترحيل جاهزة. لم يتم الاتصال بأي قاعدة بيانات.");
}

async function ensurePrepared() {
  await Promise.all([access(postgresSchema), access(migrationFile), access(lockFile)]);
}

if (mode === "prepare") await prepare();
else if (mode === "generate") {
  await ensurePrepared();
  runPrisma(["generate", "--schema", postgresSchema], { ...process.env, DATABASE_URL: process.env.POSTGRES_DATABASE_URL || localValidateUrl });
  console.log("تم توليد Prisma Client لموفر PostgreSQL. أعد pnpm db:generate قبل العودة لتشغيل SQLite محليًا.");
}
else if (mode === "validate") {
  await ensurePrepared();
  runPrisma(["validate", "--schema", postgresSchema], { ...process.env, DATABASE_URL: localValidateUrl });
}
else if (mode === "migrate") {
  await ensurePrepared();
  const target = process.env.POSTGRES_DATABASE_URL;
  if (!target || !/^postgres(?:ql)?:\/\//.test(target)) throw new Error("للتطبيق صراحةً، عرّف POSTGRES_DATABASE_URL بعنوان PostgreSQL؛ لا يستخدم هذا الأمر DATABASE_URL تلقائيًا.");
  runPrisma(["migrate", "deploy", "--schema", postgresSchema], { ...process.env, DATABASE_URL: target });
}
else throw new Error("الاستخدام: node scripts/postgresql-path.mjs prepare | generate | migrate");
